import img1 from "@/pages/faoliyat/kimyogarlar/img/1.jpg";
import img2 from "@/pages/faoliyat/kimyogarlar/img/2.jpg";
import img3 from "@/pages/faoliyat/kimyogarlar/img/3.jpg";
import img4 from "@/pages/faoliyat/kimyogarlar/img/4.jpg";
import img5 from "@/pages/faoliyat/kimyogarlar/img/5.jpg";
import img6 from "@/pages/faoliyat/kimyogarlar/img/6.jpg";
import img7 from "@/pages/faoliyat/kimyogarlar/img/7.jpg";
import img8 from "@/pages/faoliyat/kimyogarlar/img/8.jpg";
import img9 from "@/pages/faoliyat/kimyogarlar/img/9.jpg";
import img10 from "@/pages/faoliyat/kimyogarlar/img/10.jpg";
import img11 from "@/pages/faoliyat/kimyogarlar/img/11.jpg";
import img12 from "@/pages/faoliyat/kimyogarlar/img/12.jpg";
import img13 from "@/pages/faoliyat/kimyogarlar/img/13.jpg";

let dataChemists1Element = [
    {
        id:'1',
        img: img1,
        fullName: "Nodirbek Rustambekovich Yusupbekov",
        text: "Nodirbek Rustambekovich Yusupbekov kimyoviy texnologiyalarning nazariy asoslari, texnologik jarayonlar va ishlab chiqarishlarni avtomatlashtirish hamda boshqarish sohasida atoqli olim. Oʻzbekistonda xizmat koʻrsatgan fan arbobi, fan va texnika sohasida Abu Rayhon Beruniy nomidagi Oʻzbekiston Respublikasi Davlat mukofoti laureati, Oʻzbekiston Respublikasi Fanlar akademiyasining akademigi, texnika fanlari doktori, professor, akademik.\n" +
            "N. Yusupbekov 1940 yil 7 yanvarda Toshkent shahrida ziyoli oilasida tavallud topdi. Uning otasi - Yusupbekov Rustambek (Rustambek domla) 1907 yilda oʻzbek tilini oʻrganish uslubiyatini yaratgan hamda «Ta'limi avval» alifbosi va «Ta'limi soniy» oʻqish kitoblarinn yozgan pedagog. Onasi Yusupova Xabiba - Oʻzbekistonda xizmat koʻrsatgan oʻqituvchi, kahramon ona. 45 yil boshlangʻich sinf oʻqituvchisi boʻlib ishlagan va oʻsha davrdagi Lenin ordeniga sazovor boʻlgan birinchi oʻzbek ayollaridandir. Turmush oʻrtogʻi Charos Yusupbekova Toshkent davlat texnika universitetida «Umumiy kimyo» kafedrasi dosenti lavozimida uzoq yillardan beri samarali faoliyat yuritib kelmoqda. Ular bugungi kunda turli sohalarda oʻz faoliyatlarini namunali olib borayotgan uch nafar farzandni tarbiyalab, voyaga etkazishdi.\n" +
            "N.Yusupbekovning ilmiy, pedagogik, ishlab chiqarish va jamoatchilik faoliyati 1962 yilda oʻzi tamomlagan Toshkent politexnika institutidan boshlandi. Talabalik yillaridayoq uning tashkilotchilik va ilmiy qobiliyati namoyon boʻldi. U talabalar ilmiy jamiyati ishlari va oliy oʻquv yurtining jamoatchilik hayotida faol qatnashdi. 1961-1963 yillarda Toshkent politexnika instituti talabalar kasaba uyushmasini boshqardi.\n" +
            "1962 yildan ToshPI «Fizikaviy kimyo» kafedrasining assistenti, 1963 yildan 1965 yilgacha esa «Kimyo texnologiyasining jarayonlari va apparatlari» kafedrasining aspiranti boʻldi. 1966 yilning yanvarida texnika fanlari nomzodi ilmiy darajasini olish uchun dissertasiyani muvaffaqiyatli himoya qildi. U olib borgan tadqiqot natijalari respublikada yangi ilmiy yoʻnalish shakllanishiga, avtomatik nazorat va texnologik jarayonlarni boshqarish sistemalaridagi suyuq mahsulotlar sifati (qovushqoqlik, zichlik va boshqa parametrlar) ni oʻlchagichlarni oʻrganish va yaratishga asos soldi.\n" +
            "1966 yilda N.Yusupbekov «Kimyo texnologiya jarayonlarini avtomatlashtirish va kompleks mexanizasiyalashtirish» kafedra¬sining mudiri boʻldi va 1967 yilda esa unga ushbu kafedraning dosenti ilmiy unvoni berildi.\n" +
            "1970\tyildan 1973 yilgacha boʻlgan davrda N.Yusupbekov Oʻzbekiston yosh olimlar uyushmasiga raislik qildi. Uning tashabbusi bilan yosh olimlar uchun mukofotlar ta'sis etilib, talabalar ilmiy jamiyatining ishi yangi sifat bosqichiga koʻtarildi va keng koʻlamdagi «Yoshlarning ilmiy-texnik ijodiyoti» harakatining yutuqlari yosh olimlar va mutaxassislarning turli xalqaro va respublika miqyosidagi forumlari va anjumanlarida yuqori baholandi hamda xalq xoʻjaligi yutuqlari koʻrgazmalarida namoyish etildi.\n" +
            "1971 yilda N.Yusupbekov texnika fanlari doktori ilmiy darajasini olish uchun dissertasiyani muvaffaqiyatli himoya qildi. Doktorlik dissertasiyasida kimyoviy texnologiyaning yangi ilmiy yoʻnalishlaridan biri - kimyoviy kibernetikani rivojlantirdi va oʻsha yillarda mamlakatimizning eng yosh texnika fanlari doktorlaridan biri boʻldi. U aspirant va mustaqil tadqiqotchilar bilan sermahsul ish olib bordi va 1973 yilda unga «Kimyo texnologiyasi jarayonlari va ishlab chiqarishni avtomatlashtirish» kafedrasi professori ilmiy unvoni berildi.\n" +
            "Mehnat faoliyati davomida olib borgan tinimsiz izlanishlari, fan sohasida erishgan yutuqlari uchun 1980 yilda N.Yusupbekovga «Oʻzbekistonda xizmat koʻrsatgan fan arbobi» unvoni berildi.\n" +
            "Ma'rifatchilik an'analarini davom ettirib, N.Yusupbekov darslik va oʻquv qoʻllanmalar yoza boshladi. U 15 ta monografiya, 18 ta darslik va oʻquv qoʻllanmalar, 180 ta ixtiro va 440 dan ortiq ilmiy maqolalar muallifidir. Uning rahbarligida 80 dan ortiq fan nomzodlari va 20 nafar fan doktorlari tayyorlangan.\n" +
            "Uning oʻzbek tilidagi darsliklari: «Avtomatika va ishlab chiqarish jarayonlarini avtomatlashtirish» va «Texnologik jarayonlarni boshqarish sistemalari» 1983 va 1998 yillarda, lotin grafikasida yozilgan «Elektron hisoblash mashinalarini kimyo texnologiyasida qoʻllash» 2011 yilda oliy oʻquv yurtlari uchun eng yaxshi darslik deb tan olindi. «Kimyoviy texnologiya asosiy jarayonlari va apparatlari» darsligi esa 2004 yilda oʻzbek tilidagi eng yaxshi darslik respublika tanlovida ikkinchi oʻringa sazovor boʻldi.\n" +
            "2000 yilda rus tilida va 2004 yilda oʻzbek tilida chop etilgan «Optimallashga kirish» oʻquv qoʻllanmasida N.Yusupbekov tomonidan Toshkent davlat texnika universiteti talabalariga va rossiyalik etakchi oʻqituvchilar - texnika fanlari doktori, professor B.C.Balakirev va M.E.Volkovalar tomonidan Moskva Davlat muhandislik ekologiyasi universiteti talabalariga kimyo texnologiyasi jarayonlari va sistemalarini optimallash boʻyicha ma'ruza oʻqish tajribalari aks ettirilgan.\n" +
            "N.Yusupbekov tomonidan oʻzbek tilidagi «Texnologik jarayonlarni nazorat kilish va avtomatlashtirish» darsligining uchinchi qayta ishlangan va qoʻshimcha toʻldirilgan nashri 2011  yilda lotin imlosida chop ettirilgan boʻlib, unda sanoatni avtomatlashtirishning yangi tajribalari umumlashtirilgan.\n" +
            "N.Yusupbekov rahbarlik qilayotgan kafedra oliy oʻquv yurtining eng yaxshi kafedrasi tanlovlarida bir necha bor birinchi oʻrinni egallagan va eng etakchi kafedralardan biri sifatida tan olingan. Kafedra tarkibida sanoatni avtomatlashtirish buyicha dunyo liderlari - «Honeywell» (AKSh) va «Siemens» (GFR) firmalarnning avtomatlashtirishni ilgʻor texnikalari bilan ta'minlangan oʻquv-texnik va trening markazlari faoliyat koʻrsatadi.\n" +
            "1992 yilda oliy ta'lim rivojiga qoʻshgan ulkan xissasi uchun N.Yusupbekov Xalqaro oliy maktab fanlar akademiyasining haqiqiy a'zosi (akademigi) etib saylandi.\n" +
            "N.Yusupbekov - kimyo texnologiyasi, analitik va ilmiy asbobsozlik hamda kimyoviy texnologiya jarayonlari va ishlab chiqarishni avtomatlashtirish sohasida yirik ilmiy maktab asoschisi. Uning ilmiy uslubiga, avvalo, tadqiq qilinayotgan hodisaning fizikaviy tasvirlarini oʻrganish, fan va texnikaning fundamental qonuniyatlari bilan oʻzaro bogʻliqliklarini anglashga intilish kabi xususiyatlar xarakterlidir. Unga xos bulgan intilishlar murakkab ilmiy muaammolar va masalalarni echishning eng optimal yoʻllarini topadi. Tabiiy fanlar sohasidagi chuqur ensiklopedik bilim, ilmiy izlanishlarning keng arsenaldagi zamonaviy analitik usullarini bilish, nostandart tajriba ishlarining qoʻyilishiga boʻlgan doimiy intilish - bularning barchasi unga kimyo texnologiyasining nazariy asoslari, analitik asbobsozlik va ishlab chiqarish jarayonlarini avtomatlashtirish sohalaridagi sermahsul ilmiy faoliyatini yuqori malakali ilmiy va muhandis-texnik kadrlarni tarbiyalash, yuqori samarali jarayon va apparatlar, nazorat-oʻlchov asboblari va informasion-boshqaruv sistemalarini yaratish va ularni mamlakatimizning yirik sanoat korxonalarida amalda tatbiq etish boʻyicha tinmay olib borayotgan ishlari bilan muvaffaqiyatli uygʻunlashtirish imkonini beradi.\n" +
            "Oʻtgan asrning 60-yillarida N.Yusupbekov tomonidan kimyo texnologiyasi sohasida tizimli tahlil va hisoblash texnikasining yangi ilmiy usullarini qoʻllashga asoslangan ilmiy tadqiqotlar rivojlantirildi. Ushbu ilmiy tadqiqotlar doirasida kimyo, neft-kimyo, oziq-ovqat, mikrobiologiya va kimyoviy farmasevtika sanoatining tipik texnologik jarayonlarini matematik  modellashtirish, murakkab texnologik kompleks va qurilmalarni tahlil qilish va sintezlash, energiya-texnologik qurilmalar va turli murakkablik darajalariga ega boʻlgan agregatlarda yuz beruvchi jarayonlarni optimallashning murakkab masalalari muvaffaqiyatli echilgan.\n" +
            "N.Yusupbekov ilmiy rahbarligida turli konstruksiyali apparatlarda yuz beruvchi murakkab kimyoviy texnologik jarayonlar, anizatrop kapilliyar - gʻovak jismlardan erituvchini haydash, distillyasiyalash, rektifikasiyalash va bugʻlatish yoʻli orqali ikkilamchi issiqlik tashuvchining nisbatan kichik entalpiyasi bilan koʻp komponentli eritmalarni konsentrasiyalash, sochiluvchan qattiq materiallarni quritish, sochiluvchan qattiq jismlarni qovurish, namlash va kondisiyalash, siqiluvchan choʻkmalarni hosil qilish orqali suspenziyalarni filtrlash, reaksiyaviy ajratuvchi qoʻshma jarayonlar, antibiotik va boshqa tibbiy preparatlarning fermentasiya va biosintez jarayonlarini matematik modellashtirish va optimallash usullari yaratilgan.\n" +
            "Akademik N.Yusupbekov tomonidan rektifikasiyalashning sanoat jarayonlarini takomillashtirish, shuningdek, qoʻshma reaksiyaviy ajratish jarayonlari va sistemalarining koʻpgina amaliy masalalari echilgan. Tajriba - sanoat va ishlab chiqarish qurilmalarida qoʻshma reaksiyaviy ajratish jarayonlarini amalga oshirishda ilmiy-tadqiqot va sinov-konstruktorlik ishlarini oʻtkazishning nazariy asoslari ifodalangan, ajraluvchi aralashmalarning ideal emasligi hisobga olingan holda koʻp komponentli aralashmalar uchun qoʻshma reaksiyaviy ajratish kurilmalar faoliyati, qoʻshiluvchi kimyoviy reaksiyalarning kaytariluvchanligi, issiqlik va massa uzatish hamda oʻzapo ta'sirlashuvchi but va suyuqlik oqimlari real gidrodinamik strukturalarini matematik modellashtirishning eng muhim masalalari echilgan.\n" +
            "N.Yusupbekovning mazkur sohada erishgan yuqori ilmiy va amaliy yutuqlari belgisi sifatida 1983 yilda unga va uning shogirdlari V.P.Akimyonko, Sh.M.Gulomov, G.Yu.Izakson, F.S. Muxaramov, P.N.Safronov, A.K.Ubaydullaev, A.A.Chimishkyanlarga avtomatlashtirilgan boshqarish sistemalaridan foydalanib, himoya qiluvchi kimyoviy vositalarni ishlab chiqarish boʻyicha unifikasiyalashgan texnologik komplekslarni yaratganligi va amaliyotga tatbiq etganliklari uchun fan va texnika sohasida Beruniy nomidagi Davlat mukofoti berildi.\n" +
            "N.Yusupbekovning ilmiy maktabi tomonidan taklif etilgan analitik boshqaruvning farqi joriy ishlab chiqarish vaziyatlarini Soft - Computing texnologiyasi (yumshoq hisoblashlar texnologiyasi) doirasida Data Mining (ma'lumotlarning intellektual tahlili) vositasi orqali ishlab chiqiluvchi retrospektiv ma'lumotlar (ishlab chiqarish sinovi) ni chuqur sifatli tahlil qilish natijalari bilan monitoring qilish asosida mas'ul shaxslar tomonidan shakllantiriluvchi operativ boshqaruv qarorlarining uygʻunligidan iborat. Boshqarish ob'ektlarining rivojlanishi tizimli aniqlangan, informasion-boshqaruv sistemalarining faoliyat koʻrsatishi va amalga oshirilish jarayonlari shakllantirilgan boʻlib, boshqaruvning barcha sathlarida qoʻllaniluvchi qarorlarning asoslanganligi va darajasini oshiradi hamda sanoat korxonalari ishining yuhori samaradorligini ta'minlaydi.\n" +
            "N.Yusupbekov ajoyib tashkilotchi ham hisoblanadi. Uning rahbarligida yaxshi texnik va uslubiy-oʻquv laboratoriyalari bilan ta'minlangan «Ishlab chiqarish jarayonlarini avtomatlashtirish» kafedrasi Toshkent davlat texnika universitetidagi eng yaxshi kafedralardan biriga aylandi. 1980-1986 yillarda Toshkent politexnika institutining Avtomatlashtirilgan boshqarish sistemalari fakultetini boshqarib, oʻquv jarayonining moddiy bazasini mustahkamladi va respublikada birinchi boʻlib, oʻsha vaqtning eng katta quvvatli elektron hisoblash mashinalaridan biri oʻrnatilgan hisoblash markazini tashkil etdi.\n" +
            "1989 yilda Toshkent politexnika instituti tarkibidan Toshkent mashinasozlik instituti ajralib chikdi va uning birinchi rektori etib N.Yusupbekov saylandi. 1991 yilda Toshkent mashinasozlik instituti bazasida Toshkent politexnika instituti tarkibidan ajralib ketgan mustaqil oliy oʻquv yurtlari (Toshkent kimyo-texnologiya va Toshkent arxitektura-qurilish institutlari) dan keyin uning qolgan fakultetlari birlashtirilib, Abu Rayhon Beruniy nomidagi Toshkent davlat texnika universiteti tashkil topdi va N.Yusupbekov uning birinchi rek¬tori boʻldi. Bu erda uning rahbarligida Kadrlar tayyorlash milliy dasturining birinchi bosqichini amalga oshirish, universitetning moddiy-texnik bazasini mustahkamlash va oʻquv jarayoniga ilgʻor pedagogik texnologiyalar va hisoblash texnikasining zamonaviy vositalarini keng tatbiq etish boʻyicha ishlar amalga oshirildi. Respublikada birinchi boʻlib kirish imtihonlarini kompyuterlarda avtomatlashtirilgan tarzda qabul qilish tashkil etildi.\n" +
            "Fan va texnika boʻyicha Davlat qoʻmitasi shakllantirilgandan soʻng 1992 yilda Oʻzbekiston Reepublikasi Prezidentining Farmoni bilan N. Yusupbekov qoʻmitaning birinchi raisi etib tayinlandi. Qoʻmitada ishlash vaqtida u fan-texnika davlat dasturi tizimini yaratdi. Uning intilishlari tufayli intellektual mulkni himoya qilishning milliy tizimi va uning respublikadagi organi - Davlat patent idorasi shakllantirildi.\n" +
            "Nodirbek Rustambekovichning xizmatlari ilmiy jamoatchilik tomonidan yuqori baholangan. Muhandislik yutuqlariga koʻra, 1992 yilda Xalqaro injenerlik akademiyasining haqiqiy a'zosi etib saylandi. Ilmiy yutuqlari va ularni ishlab chiqarishga tatbiq etganligi uchun u 1994 yilda Oʻzbekiston Reepublikasi Fanlar akademiyasining muxbir a'zosi etib saylandi.\n" +
            "1994 yilda N. Yusupbekov Oʻzbekiston kimyo sanoati korxonalari uyushmasi «Oʻzkimyosanoat» boshqaruvi raisi etib tayinlandi. Uning rahbarlik yillarida kimyo sanoatida nafaqat ishlab chiqarishning barqarorligiga, balki ularning oʻsishiga ham erishildi. 1993 yilda hukumat tomonidan tasdiqlangan 1998-2002 yillar davomida Oʻzbekiston kimyo sanoati korxonalarining kompleks rivojlanish Dasturi ishlab chiqildi. Dasturning asosiy yunalishlari xalq xoʻjaligining kimyo va unga turdosh sohalarida xomashyo mustaqilligiga erishish va ishlab chiqarishni qayta strukturalashtirish hisoblanadi. Sanoat rivojiga qoʻshgan hissasi uchun N.Yusupbekov 1999 yilda «Doʻstlik» ordeni bilan mukofotlandi.\n" +
            "2000 yilda N.Yusupbekov Oʻzbekiston Respublikasi Fanlar akademiyasining akademigi etib saylandi. 2001 yilda u Toshkent kimyo-texnologiya instituti rektori etib tayinlandi. 2004 yildan esa ToshDTUga qaytib, «Ishlab chiqarish jarayonlarini avtomatlashtirish» kafedrasida rahbarlikni davom ettirdi. Milliy patent tizimini tashkil etganligi va xalqaro hamkorlikni rivojlantirganligi, shuningdek, asbobsozlik va boshqarish sistemalari sohasida birinchi oʻrinda turuvchi eng muhim ilmiy- texnik ishlanmalari uchun 2004 yilda N.Yusupbekov Xalqaro intellektual mulk tashkiloti (XIMT) ning yuksak mukofoti - Oltin medal bilan taqdirlandi.\n" +
            "N.Yusupbekov 2000 yildan boshlab «Sanoat avtomatlashtirishida intellektual sistemalar» (World Conference on Intelligent Systems for Industrial Automation - «WCIS») Xalqaro ilmiy konferensiyaning tashabbuskori va tashkilotchisi hisoblanadi. Oʻtgan davr ichida Toshkentda konferensiyaning ettita ilmiy forumi oʻtkazilib, ularda sun'iy intellekt nazariyasi, noaniq toʻplamlar nazariyasi usullari, sun'iy neyron tarmoqlari, genetik algoritmlar, assosiativ xotira va bilimlarga ishlov berishning ekspert sistemalari sohasidagi etakchi olim va mutaxassislarning ishlari qabul qilindi.\n" +
            " 2002 da N.Yusupbekov tashabbusi bilan Toshkent kimyo-texnologiya institutida chop etiladigan «Kimyo va kimyo texnologiyasi» respublika miqyosidagi ilmiy-texnik jurnal, 2004 yilda esa ToshDTUda chop etiladigan «Kimyoviy texnologiya. Nazorat va boshqaruv» xalqaro miqyosdagi ilmiy-texnik jurnallari tashkil qilindi. U «Rossiya Federasiyasi oliy oʻquv yurtlari xabarnomasi», «Asbobsozlik» va «Energetika va informatika muammolari» jurnallari tahririyat hay'atining a'zosi hisoblanib, «Kimyoviy texnologiya. Nazorat va boshqaruv» jurnalining tahririyat hay'atini boshqarib kelmoqda.\n"
    },
    {
        id:'2',
        img: img2,
        fullName: "Abduxamid G'ofurovich Maxsumov",
        text: "Abduhamid Maxsumov 1936 yil 10 mart kuni Toshkent shahrining Chigʻatoy (hozirgi Forobiy) koʻchasida dunyoga keldi. U 1944-1954 yillarda 111-maktabda tahsil oldi. 1954 yilda Oʻrta Osiyo politexnika institutining kimyo-texnologiya fakultetiga oʻqishga kirib, 1959 yilda tugatdi va «Oʻsimlik yogʻlari texnologiyasi» mutaxassisligiga ega boʻldi.\n" +
            "Oʻsha yili OʻzFA «Polimerlar kimyosi» ilmiy- tekshirish institutiga yoʻllanma bilan ishga yuborildi va oʻz mehnat faoliyatini katta laborantlik lavozimida boshladi.\n" +
            "Abduhamid Maxsumov 1961 yilda Moskvadagi sobiq Ittifoq FAning akademik A.N.Nesmeyanov nomidagi «Elementoorganik birikmalar» ilmiy-tekshirish instituti aspiranturasiga kiradi. Akademik V.V.Korshak va professor A.M.Sladkovlarning ilmiy rahbarliklarida «Tarkibida uchbogʻ saqlangan poliefirlarning sintezi va xossalari» mavzusidagi nomzodlik dissertasiyasini tayyorladi va 1964 yilda uni muvaffaqiyatli himoya qiladi.\n" +
            "Abduhamid aspiranturadan soʻng Toshkentdagi OʻzFA «Paxta sellyuloza texnologiyasi» ilmiy-tekshirish institutida kichik ilmiy xodim, 1964 yilda katta ilmiy xodim lavozimida ishladi. Oʻsha yili Oʻrta Osiyo neftni kayta ishlash ilmiy-tekshirish  instituti (SredazNIINP) ga oʻtdi va katta ilmiy xodim boʻlib ishladi. 1968 yilda shu institutning «Organik sintez» laboratoriyasi mudiri lavozimiga saylandi.\n" +
            "SredazNIINP direktori, akademik, oʻz zamonining etuk kimyogari Abdulla Sultonovich Sultonov ilmiy ishlarini bajarish va rivojlantirishda Abduhamid Gʻofurovichga katta e'tibor qaratdi va shart-sharoit yaratib berdi. Shu sababli uning Sredaz NIINPdagi b yillik faoliyati serqirra va sermazmun boʻldi. natijada u 7 nafar kimyo fanlari nomzodlarini tayyorladi: 75 dan ortiq ilmiy maqolalar va 50 dan ortiq ixtirolar e'lon qildi.\n" +
            "1971 yilda Abduhamid Maxsumov ToshMI «Organik kimyo» kafedrasiga dosent lavozimiga ishga oʻtdi. 1972 yilda shu kafedraga mudir boʻlib saylandi. Kafedrada oʻquv-uslubiy jarayon yaxshi yoʻlga qoʻyildi, ilmiy ishlar boshlab yuborildi va tez orada kafedra institutning eng ilgor kafedralaridan biriga aylandi. Abduhamid Maxsumov Tibbiyot institutida ishlash faoliyati davomida akademik K.A.Zufarov, akademik U.O.Oripov, professor O.S.Maxmudov, professor N.X.Shomirzaev, akademik T.O.Daminov (institut rektorlari) rahbarligida kafedrani boshqardi. Ular «Bioorganik va bioanorganik kimyo» kafedrasini zarur asbob-anjomlar, kimyoviy ashyolar va reaktivlar, ta'lim va ilmiy-texnikaviy jihozlash yuzasidan juda katta yordam berib qullab-quvvatlab keldilar. Bu oʻrinda shuni ta'kidlash kerakki, kafedra, oʻquv-uslubiy, ilmiy-tarbiyaviy ishlar boʻyicha institutning musobaqa va tanlovlarida koʻp marotaba gʻolib boʻldi va qimmatbaho mukofotlar bilan taqdirlandi.\n" +
            "Organik kimyo sohasining oʻtkir bilimdoni va ayni vaqtda shu fan fidoyisi boʻlgan Abduhamid Gʻofurovich ijodkor, yangilik yaratuvchi olim, tajribali pedagog, mohir ustoz, mehribon murabbiy sifatida talabalarga, yosh ixtirochi, akademik liseylar va tibbiyot kollejlari oʻqituvchilari, malaka oshirish kurslari tinglovchilariga kimyodan saboq berishdagi mazmunli ma'ruzalari bilan hurmatga sazovordir.\n" +
            "Abduhamid Maxsumovning zamonaviy pedagogik hamda uslubiy salohiyati va samarasini quyidagilar bilan tavsiflash mumkin: u faqat boshqalarni oʻqitish bilan cheklanmasdan, bilimi va malakasiga doimo e'tibor beradi. Kafedra xodimlari bilan birgalikda 190 dan ortiq oʻquv qoʻllanma, uslubiy qoʻllanma, ma'ruza matnlari, uslubiy tavsiyanoma va boshqa koʻrsatmalar chop etdi. Tibbiy oliy ta'lim muassasalari talabalari uchun birinchi boʻlib oʻzbek tilida «Bioorganik kimyo» darsligini tayyorladi va nashr ettirdi. Shogirdlari professorlar A.J.Juraev va U.A.Boltaboevlar bilan birinchi boʻlib bioorganik kimyodan 4- toifadagi elektron darslik yaratdi va mualliflik guvohnomasini oldi. Turli miqyosdagi ilmiy-amaliy va oʻquv-uslubiy anjumanlarda «Kimyo fanini oʻkitish uslubiyatlari va muammolari» mavzusida 70 dan ortiq ma'ruzalar bilan qatnashdi. Kafedra xodimlari bilan birgalikda «organik kimyo» sohasida qilingan 110 dan ortiq ixtirolarni oʻquv jarayoniga joriy qilish bilan birga yangi ilgʻor pedagogik texnologiyalar, oʻqitish metodikalarini ta'lim jarayoniga kiritdi. U hamkasblaridan oʻquv jarayonini tashkil etishda ba'zi bir muomala koʻnikmalarini mustaqil qarorlarni qabul qilishni, oʻz faoliyati natijalarini tanqidiy baholashni talab qildi.\n" +
            "Abduhamid Maxsumov 42 yillik pedagogik faoliyatida mamlakatimizning ijtimoiy-siyosiy, iqtisodiy va madaniy hayotida sodir boʻlayotgan tub oʻzgarishlar, istiqboldagi ulkan vazifalarni keng va chuqur anglagan, tahlil qilgan holda talaba yoshlarni milliy istiqlol gʻoyasi asosida tarbiyalashga amaliy va ma'ruza darslarda mashgʻulotlardan tashqari vaqtda hamda talabalar uylarida katta ahamiyat berdi va ushbu ma'naviy-ma'rifiy ishlarda doimo oldingi saflarda boʻldi.\n" +
            "Chuqur bilim egas, sermahsul olim Abduhamid Gʻofurovich kafedrada ilmiy- izlanish ishlarini yuqori sifat va saviyada olib borishga erishdi va buning natijasida sintez qilingan yangi biologik faol moddalar sonini hozirgi kunda 25000 taga etkazdi. Yaratilgan kimyoviy birikmalarning biologik, fiziologik, farmakologik va boshqa xossalariga e'tibor qaratsak, ulkan ilmiy izlanishlarning ilk bor sintezi tarkibida uch bogʻ va «ON» guruhini saqlagan toʻyinmagan spirt-propargil spirti asosida yangi usullar yaratilganligini hamda adabiyot va patentlarda ma'lum boʻlmagan yangi birikmalar sintez qilinganligini koʻramiz.\n" +
            "Hozirgi zamonaviy nozik organik sintez kimyosi, albatta, boshqa fanlar va sohalar bilan birgalikda rivojlantiriladi. Barcha sintez qilingan birikmalarning biror-bir xossalarini aniqlash uchun ularning turli biologik, fiziologik, texnik va boshqa xossalari oʻrganiladi. Natijada biron-bir xususiyatga eta boʻlgan son-sanoqsiz yuqori samarali raqobatbardosh faol moddalar aniqlanadi va ular tegishli sohalarda koʻllaniladi.\n" +
            "Abduhamid Gʻofurovich yaratgan 40 dan ortiq biologik, farmakologik birikmalar xalq xoʻjaligining turli sohalarida amaliyotga tatbiq etildi.\n" +
            "2007 yilda Abduhamid Maxsumov Nizomiy nomidagi Toshkent davlat pedagogika universitetining «Kimyo va uni oʻqitish metodikasi» kafedrasiga professor lavozimiga ishga oʻtdi. Universitetda ham yuqori unum bilan boy milliy madaniy-tarixiy an'analarga va xalqimizning intellektual merosiga hurmat bilan qaragan holda faoliyat koʻrsatib kelmoqda. Bakalavr va magistrlarga namunali ma'ruzalar oʻqimoqda, ilmiy ishlar yuqori darajada olib borilmoqda. 6 yil ichida 330 dan ortiq ilmiy ishlar chop qildirdi, yoshlarni ilmiy ishlarga jalb qildi. 300 dan ortiq yoshlar maqolalar chop qilishdi va qilishmokda.\n" +
            "Professor Abduhamid ¬Gʻofurovich Maxsumovning ilmiy izlanishlari natijalari 160 ta ishda oʻz aksini topdi. U 1100 dan ortiq ilmiy maqolalar, 300 ta ixtiro va patentlar, 6 ta darslik, 200 dan ortiq oʻquv-uslubiy qoʻllanmalar muallifidir. Uning 50 yillik ilmiy-pedagogik  faoliyati rahbarligi ostida 7 ta doktorlik, 40 ta nomzodlik dissertasiyalari himoya qilindi. 1979 yilda ilmiy ishlarda erishgan yutuqlarini inobatga olib, unga «Oʻzbekistonda xizmat koʻrsatgan ixtirochi» unvoni berilgan. 2000 yilda «Yilning eng yaxshi ilmiy rahbari» va 2002 yilda «Yilning eng yaxshi murabbiysi» unvonlariga sazovor boʻldi.\n"
    },
    {
        id:'3',
        img: img3,
        fullName: "Sa'dulla Iskandarov",
        text: "Sa'dulla Iskandarov 1939 yil 5 fevralda Xorazm viloyati Bogʻot qishlogʻida tugʻilgan.\n" +
            "Toshkent Farmasevtika institutini tugatgan (1961 yil). Oʻzbekiston FA Oʻsimlik moddalari kimyosi institutida aspirat, kichik, katta ilmiy xodim (1962-1973 yillar), Xorazm Pedagogika instituti oʻquv-ilmiy ishlar boʻyicha prorektori (1973-1977 yillar), Oʻrta Osiyo neftni kayta ishlash ilmiy-tadqiqot instituti direktori (1977-1978 yillar), Toshkent Irrigasiya va qishloq xoʻjaligini mexanizasiyalashtirish injenerlari instituti rektori (1978-1986 yillar), kafedra, laboratoriyalar mudiri (1987-1991 yillar, 2001- 2007 yillar), Toshkent Farmasevtika instituti rektori (1991-1993 yillar, 1994-2000 yillar), «Oʻzfarmsanoat» DAK boshqaruvi raisi (1993-1994 yillar), Oʻzbekiston FA Oʻsimlik moddalari kimyosi instituti direktori maslahatchisi va Oʻzbekiston Kimyo-farmasevtika ilmiy- tadqiqot instituti bosh ilmiy xodimi vazifalarida 2007 yildan beri ishlab kelmoqda. Oʻzbekiston FA muxbir a'zosi (1989 yil), akademigi (2000 yil), Oʻzbekiston Qishloq xoʻjalik FA akademigi (1991 yil), kimyo fanlari doktori (bioorganik kimyo, 1973 yil), professor (1980 yil).\n" +
            "S.Iskandarov ilmiy ishlari oʻsimliklar tarkibidagi fiziologik faol moddalarni tadqiq qilish, oʻsimliklarning oʻsish jarayonini boshqarish, yangi biologik faol moddalarni sintez, tahlil qilish usullarini yaratish va tibbiyot, qishloq xoʻjaligi uchun yuqori samarali preparatlar kashf etish hamda yangi texnologiyalar yaratishga bagʻishlangan. U mamlakatimiz hududida keng tarqalgan leontipe, termopsis oʻsimliklarining turlarini tadqiq etib, ajratilgan 24 ta yangi alkaloidlarning kimyoviy tuzilishi va stereokimyosini aniqlash davomida yangi izlanish metodlarini yaratgan. Adabiyotda ma'lum boʻlmagan getero-xalqali alkaloidlarning yangi guruhi hamda xinolizidin alkaloidlarining bimolekulyar qatori mavjudligini ochgan. Alkaloidlarning stereokimyosini oʻrganishda molekulalarning istalgan S - N bogʻlari oʻrniga S - D bogʻlarini almashtirish usullarini ishlab chiqish, getero-halqalarning turli atomlariga izotoplar almashtirib, ularning bir qator izomerlariga kuchli elektronlar tarami bilan bombardimon qilganda sterik effekt namoyon boʻlishini ochgan. Tarkibida laktam, alfa-inridon halqalarini saqlagan alkaloidlarning absolyut konfigurasiyalarini aniqlashning spektro-iolyarimetriya usulini yaratgan. Leontipe va termopsis oʻsimliklari turlaridan ajratib olingan alkatoidlar summasidan bimolekulyar qatorga mansub boʻlgan yangi alkaloidlar ajratib olib, ularning tuzilishini sintez yoʻli bilan tasdiqlab, alkaloidlar oʻsimlik oʻsishi, rivojlanishi jarayonida muhim rol oʻynashi va organizmda faqatgina monomolekula holidagina emas, balki biopolimerlar tarkibida ham boʻlishi mumkinligini bashorat qilgan. Akademik O.Sodiqov maktabida oʻrganilgan goeoelin alkaloidni tuzilishi ham koʻpgina bahslarga sabab boʻlsa-da, uning bimolekulyar tuzilishga mansub ekanligini adabiyotda ma'lum alkaloid sofokarpindan sintez qilib, uzil-kesil tasdiqlagan. Akademik A.P. Orexov maktabida leontidin alkaloidi 1930 yillarda ajratilgan boʻlib, qariyb 40 yil davomida oʻrganilib, 6 ta gipotetik kimyoviy struktura taklif qilingan. Leontidinning kimyoviy tuzilishi zamonaviy elektron optik, radiospektroskopiya usullaridan foydalanib, uning tabiiy azobirikmalar yangi guruhining birinchi namunasi ekanligini aniqlagan va uchrashuv sintezini amalga oshirib, leontidin - 1.3 - kondensirlashgan xinolizido - indolizidin guruhining dastlabki namoyandasi ekanligini tasdiqlagan.\n" +
            "1980 yildan boshlab Ittifoqda birinchi boʻlib, paxtachilikda kimyolashtirish jarayonlarini optimallashtirish laboratoriyalar kompleksini tashkil qilgan, paxtaning oʻsishi, rivojtanish, hosil yigʻilishi stimulyatori A – 1, Ketostim preparatlari, yuqori samarali «Optim», «Optim - 2» defoliantlari va pillachilikda yuqori samarali biostimulyatorlar – «Baraka», «Mikrofit» preparatlarini kashf etib qishloq xoʻjaligiga joriy etgan. 2005 yildan paxtachilik va donchilikda keng miqyosda qoʻllanilayotgan yangi «Bahor» preparatining turli kompozisiyalarini hamda 2010 yilda donchilik uchun yuqori samarali fungisid «Qalqon» preparatini ixtiro qilgan. Ular mamlakatimizda ishlatilayotgan xorijiy preparatlardan faolligi 4-6 baravar yuqoriligi, kam zaharliligi, ekologik xavfsizligi, universal funksiyali ta'siri ustunligi tufayli keng koʻlamda paxtachilikda va donchilikda muntazam qoʻllanilmoqda. Shu bilan birga paxtachilik va donchilikda katta muammolarga olib keluvchi fuzarnoz kasalligiga qarshi qoʻllaniluvchi yangi preparat sintez qilingan va dala sinovlaridan muvaffaqiyatli oʻtmoqda.\n" +
            "Tibbiyotda keng koʻlamda ishlatilib kelinayotgan levomisetin va K, E vitaminlarini ishlab chiqarishda yangi texnologiyalar uchun zarur boʻlgan bir qancha yarim tayyor mahsulotlar: para- nitroasetofenon, naftaxinon, mono-, dixlorbenzoy kislotalarini Germaniya, Rossiya va Ukraina buyurtmalari asosida ishlab chiqarish texnologiyalarini yaratgan.\n" +
            "Respublikamiz florasi koʻpgina noyob oʻsimliklar turlari va ularning etarli zaxiralariga ega boʻlgani uchun tarkibidagi fiziologik faol moddalar majmuaviy tarkibidan nafakat individual moddalarni, balki oʻzaro antagonist boʻlmagan, hattoki bir-birining ta'sir kuchini oshiradigan, ma'lum fraksiyalarni ajratib olish texnologiyalari yaratilgan. Shu bilan birga koʻpgina noyob davolovchi preparatlarning nojoʻya ta'sirlarini minimallashtirish maqsadida ularning analogik ta'sirga ega bulgan toʻgʻri tabiiy moddalar bilan birgalikda kam dozada qoʻllaniluvchi yuqori samarali kompozipiyalarini yaratish ishlari amalga oshirilmoqda.\n" +
            "Keksayish jarayoni boshlanmasdan turib, hayotiy muhim ichki a'zolar (yurak qon-tomir tizimi a'zolari, jigar, buyrak, oshqozon osti bezi, jinsiy a'zolar va h.k.) kasalliklarining oldini olishda qoʻllaniladigan noyob, spesifik ta'sirlarga ega boʻlgan, tabiiy manbalar asosida olingan, keng ta'sir doirali, xavfsiz dori preparatlari majmuasini joriy etish dolzarb muammodir. Olib borayotgan ilmiy izlanishlar ushbu muammolarning echimiga qaratilgan ilk qadamlar hisoblanadi. Jamiyat a'zolarining keksayib borishi kuzatilayotgan hozirgi paytda kishilar faol hayotini uzaytirish, mehnatga yaroqsiz boʻlgan keksa kishilar salomatligini yaxshilash uchun kerak boʻladigan qoʻshimcha xarajatlarning kamayishiga olib keladi.\n" +
            "Koʻp yillar muammo boʻlib kelgan, ming yillik xalq tabobatining tojdori mumiyo preparatlariga yoʻl ochgan, mumiyo substansiyasining olinish texnologiyasini birinchi boʻlib yaratishga va shu asosda «Mumiyo», «Stimusol» tabletkalarini tibbiyotga joriy etishga muyassar boʻlgan. Xalq tabobatida keng ishlatiladigan kurkuma, sofora, qizilmiya oʻsimliklari asosida original preparatlar yaratgan, Ferulong - boʻgʻimlar yalligʻlanishi hamda podagra kasalliklarini davolovchi preparat sifatida tibbiyot va ishlab chiqarish amaliyotiga tatbiq etilgan. Kursetin kardioprotektor preparat sifatida klinik sinovlardan oʻtib tibbiyot amaliyotiga kirib kelmoqda. Gepaprot neo gepatoprotektor, Apyuong – prostatit va prostata adenomasiga karshi samarali preparat sifatida klinik sinovlardan oʻtmoqda.\n" +
            "S.Iskandarov ilmiy-pedagogik faoliyati davomida oliy oʻquv yurtlari talabalari va ilmiy xodimlar uchun moʻljallangan, davlat tilida birinchi marta yozilgan 2 qismdan iborat bulgan «Organik kimyo nazariy asoslari» kitobini, organik kimyo boʻyicha darslik va laboratoriya mashgʻulotlari uchun amaliy qoʻllanma, 170 dan ortiq ilmiy maqolalar chop etgan. Bundan tashqari u 70 ta mualliflik guvohnomalari, patentlar egasi. Olim 7 nafar fan nomzodlariga rahbarlik kilib, 6 ta doktorlik dissertasiyasi ishlariga maslahatchi boʻlgan.\n"
    },
    {
        id:'4',
        img: img4,
        fullName: "Raxim Sodiqovich Tillaev ",
        text: "Raxim Sodiqovich Tillaev 1927 yilda Toshkent shahrida hunarmand oilasida tugʻilgan. 1946 yilda oʻrta maktabni tugatib, Oʻrta Osiyo Davlat universitetining Kimyo fakultetiga oʻqishga kiradi va UNI 1951 yilda imtiyozli diplom bilan tugatgach, aspiranturaga tavsiya qilinadi. 1954 yilda kimyo fanlari nomzodi ilmiy darajasini olish uchun dissertasiyani muvaffaqiyatli himoya qiladi.\n" +
            "Raxim Tillaev 1954-1955 yillarda Oʻzbekiston Fanlar akademiyasi Kimyo institutida laboratoriya mudiri boʻlib ishlaydi va 1955 yildan  Toshkent Davlat universiteti Kimyo fakultetining Fizik kimyo kafedrasiga assistent boʻlib oʻtib, oʻzining ilmiy va pedagogik faoliyatini davom ettiradi. 1966 yilda doktorlik dissertasiyasini muvaffaqiyatli himoya qilib, kafedra professori va 1972 yildan 2005 yilgacha kafedra mudiri boʻlib ishlaydi. Shu yillar davomida Kimyo fakulteti talabalari uchun Fizik kimyodan va mutaxassislik fanlaridan ma'ruza hamda amaliy mashgʻulotlar oʻtkazadi.\n" +
            "Professor R.Tillaevnnng ilmiy-tadqiqot ishlari respublikamizda Fizik kimyo fanini va polimerlarning radiasion kimyosini rivojlantirishga qaratilgan edi. U sintetik polimerlarga vinil monomerlarini radioaktiv nurlar ta'sirida payvandli polimerlashning yangi usullarini ishlab chiqib, polietilen, polivinilxlorid, polistirol va boshqa qator polimerlarning payvandli sopolimerlarini sintez qildi hamda ularning fizik-kimyoviy va fizik-mexanik xossalarini urgandi. Bunda payvandli sopolimerlar eritmalari termodinamikasini oʻrganishga katta ahamiyat berildi. Payvandli sopolimer¬lar eritmalarining xossalari ularni olish sharoitlariga. komponentlar tabiati va tarkibiga: makromolekulyar parametrlarga bogʻliqligi haqida qator qonuniyatlar kashf qilindi. Bu masalalarni hal qilishda olingan natijalar termodinamik mezonlar asosida baholandi va polimerlarning termodinamik xossalariga molekulyar strukturaning ta'siri koʻrsatib berildi.\n" +
            "Kafedrada genetik va sema'ruza usullarida yaratilgan yangi nav paxta tolalarining ustmolekulyar. kristall va kapillyar - govak tuzilishi xamda termodinamik xossalarini oʻrganish sohasida jadal ilmiy-tadqiqotlar olib borildi. Sellyuloza va uning efirlari eritmalarining termodinamik, gidrodinamik, makro¬molekulyar xossalari va konformasion xususiyatlari chukur tahlil qilindi. Suvda eruvchan sellyuloza efirlari hamda tabiiy va sintetik polielektrolitlar asosida noyob xossalarga ega interpo¬limer komplekslar olish va ularning fizik - kimyoviy va termodi¬namik xossalarini oʻrganish boʻyicha tadqiqotlar oʻtkazildi.\n" +
            "R. Tillaev rahbarligida yana bir ilmiy yoʻnalish - elektrod jarayonlarning kinetikasini tadqiq qilish boʻyicha ishlar amalga oshirildi. Bu sohada turli korroziya ingibitorlari va antikorrozion qoplamalar ishtirokida elektrod jarayonlar kinetikasi oʻrganildi. Respublikamizdagi maxalliy xomashe va sanoat chiqindilari asosida kislotali va tuzli shishtlardagi korroziyaning oldini oluvchi yangi ingibitorlar va antikorrozion qoplamalar yaratildi. Jumladan, yogʻ-moy korxonalari chiqindisi hisoblangan gossipol smolasi asosida metallarning zanglashiga qarshi xossaga ega va turli maqsadlarga moʻljallangan bir necha yangi kompozisiyalar olinib, amaliyotga tatbiq etildi.\n" +
            "R. Tillaev Fizik kimyo fanidan oliy oʻquv yurtlari talabalari uchun «Misol va masalalar tuplami» va «Fizik kimyodan amaliy mashgʻulotlar» oʻquv qoʻllanmalarini rus tilidan oʻzbek tiliga tarjima qilgan va oʻnlab uslubiy qoʻllanmalar yaratgan. U polimerlarning fizik-kimyosi va termodinamika sohasida 2 ta monografiya, 400 ga yaqin ilmiy maqola e'lon qilgan. Uning ilmiy sohada qilgan ishlari kagor xalqaro va respublika ilmiy anjumanlarida (Rossiya, Yaponiya, Vengriya, Chexoslovakiya. Turkiya va h.k.) eshitilgan va muhokama qilingan.\n" +
            "U 1967 - 1968 yillarda ToshDU qoshidagi tabiiy fanlar oʻqituvchilari malakasini oshirish fakultetining dekani. 1968 - 1972 yillarda ToshL>gning ilmiy ishlar boʻyicha prorektori, 1972 yildan 2005 yilgacha universitetning Fizik va kolloid kimyo kafedrasi mudiri, umrining oxirigacha mazkur kafedra professori lavozimlarida xizmat kildi.\n" +
            "R. Tillaev OʻzMU qoshidagi va «Fan va taraqqiyot» RITK qoshidagi doktorlik dissertasiyalari himoyasi boʻyicha ixtisoslashgan ilmiy kengashlar a'zosi; «Yukori molekulyar birikmalar muammolari» boʻyicha ilmiy kengash a'zosi. «Oʻzbekiston kimyo jurnali» va «Kompozision materiallar» jurnallari redkollegiyalari a'zosi edi.\n" +
            "Professor R.Tillaevga 1981 yilda «Oʻzbekistonda xizmat koʻrsatgan fan arbobi» faxriy unvoni berilgan. U «Shuhrat» medali bilan ham takdirlangan edi.\n"
    },
    {
        id:'5',
        img: img5,
        fullName: "Qudrat Axmerovich Axmerov ",
        text: "Kudrat Axmerovich Axmerov 1937 yili Toshkentda tavallud topgan. 1955 yili Mannon Uygʻur nomli 22-oʻrta maktabni medal bilan tamomlab, Oʻrta Osiyo Politexnika institutining kimyo-texnologiya fakultetiga oʻqishga kiradi.\n" +
            "I960 yili institutni bitiradi va mazkur oliy oʻquv yurtining «Organik kimyo» kafedrasiga assistent vazifasida ishga olib qolinadi. Bir yil davomida Moskvadagi M.V.Lomonosov nomidagi Nozik kimyo-texnologiya institutining «Organik sintez texnologiyasi» kafedrasida stajirovkada boʻladi. 1962 yil mazkur institutning aspiranturasiga kiradi. 1966 yilning boshida u oʻzining asetilen bilan ammiakning yuqori haroratdagi katalitik reaksiyasini oʻrganishga bagʻishlangan nomzodlik dissertasiyasini yoqlaydi.\n" +
            "Ilm vaqtdan boshlab K.Axmerov Toshkent politexnika institutining «Organik kimyo» kafedrasida assistent, katta oʻqituvchi va 1968 yildan boshlab dosent vazifasida faoliyat koʻrsata boshlaydi. U oʻzining pedagogik faoliyatini kimyo texnologiyasi fakulteti dekani oʻrinbosari vazifasi bilan qoʻshib olib boradi. «Organik kimyo», «Asosiy organik sintez texnologiyasi» kurslari buyicha ma'ruzalar oʻqiydi va amaliy mashgʻulotlar olib boradi. Pedagogik faoliyatini ilmiy ishlarini davom ettirish bilan hamohang ravishda davom ettiradi.\n" +
            "Ma'lumki, asetilen bilan ammiak reaksiyasini dastlab oʻrgana boshlagan olim A.E.Chichibabin edn. Lekin qandaydir sabablarga koʻra endi oʻrganila boshlangan ushbu reaksiya uning diqqatidan chetda qolib ketadi. Shu bois yosh tadqiqotchi K.Axmerovning ilmiy rahbari professor R.M.Flid unga mazkur reaksiyani aspirantlik ilmiy ishi sifatida davom ettirishini taklif etadi. Kechani kunduzga ulab olib borilgan tadqiqotlar oʻz samarasini beradi, reaksiyaning kinetikasi chuqur oʻrganiladi, yangi samarali ikkita katalizator ishlab chiqarilishi ishni kichikroq hajmda boʻlsa-da, Shostkadagi kimyoviy reaktivlar korxonasida amalga oshirishga imkon beradi. \n" +
            "Etmishinchi yillarda yosh olim oʻz hamkasb doʻstlari va shogirdlari bilan birgalikda oʻrganilayotgan reaksiya va jarayonlar koʻlamini kengaytirib yuboradi. U shu jarayonlarni oʻrganishga Moskva, Chernologolovka, Novosibirsk kabi shaharlardagi ilmiy-tekshirish va oliy oʻquv yurtlari olimlari diqqatini ham jalb qiladi. Natijada asetilen bilan ammiakdan nafaqat sirka kislotasining nitrilini, balki piridin asoslarining koʻpdan koʻp xosilalarini olish ham mumkinligini koʻrsatadi. Shu yillarda nashr qilingan ilmiy maqola va monografiyalar fikrimiz tasdigʻi boʻla oladi. Xalqaro simpoziumlar, kongress va boshqa anjumanlarda qilingan ma'ruzalar koʻpchilik yirik olim va tadqiqotchilarning diqqatini tortadi. Reaksiyada hosil boʻladigan piridin asoslarining asosiy qismi koʻmirdan olinuvchi mahsulotlar oʻrnida ishlatilishi mumkinligi amalda tasdiqlanadi. Eng muhimi reaksiya chiqindilari boʻlmish yuqori molekulali birikmalar aralashmalari va azotli smolalar, qotirgichlar, buyoq elim va boshqa kerakli mahsulotlar tayyorlash uchun xomashyo sifatida amaliy ahamiyat kasb etishi ham tajribalarda isbotlanadi. Mazkur tadqiqotlar dosent K.Axmerovning 1981 yilning 23 martida Moskvadagi M.V.Lomonosov nomli Nozik kimyo texnologiya instituti (hozirgi Akademiya) da yozgan dissertasiyasiga asos boʻldi. Asetilen bilan ammiak reaksiyasini uchinchi komponent (keton, aldegid va boshqalar) ishtirokida oʻrgangan shogirdlaridan Dilmurod Yusupov va Abduvaxob Ikromovning oʻrgangan jarayonlarida sintez qilingan yangi mahsulotlar qimmatbaho metallarning turli aralashmalaridan ajratib olish (sorbsiya) xususiyatining 99-100 % ga yaqinligi ish mualliflarining ham tez fan doktori boʻlib etishuviga erishtirdi. Koreyalik tadqiqotchi Li En Xenning professor K. Axmerov ilmiy rahbarligida Sibirdagi Angarsk kimyo korxonasida neftni qayta ishlashdan hosil boʻladigan chiqindi hisoblanmish piranlarning katalitik ammonlizi reaksiyasida xomashyo sifatida qoʻllanilib kator siklik azotli birikmalar olinishiga olib keldi va uning dissertasiya ishiga asos boʻldi.\n" +
            "Saksoninchi yillar boshlarida K. Axmerovning shogirdlari bilan bajargan ilmiy ishlariga qiziqish kuchayib ketdi. Olingan koʻplab mualliflik guvohnomalari asosida besh a'zoli va olti a'zoli azotli siklik birikmalarni amaliyotga qoʻllash borasida Ittifoq kimyo sanoati vazirligining 1979 yil 22 avgustdagi 661-buyrugʻida bu ishlarni bajarishiga Toshkent politexnika instituti xodimlari bilan bir qatorda Moskvadagi Oʻsimliklarni kimyoviy himoya qilish ilmiy-tadqiqot instituti, Kimyoviy fizika ilmiy-tadqiqot instituti katalitik jarayonlari texnologiyasi boʻlimi va M.V.Lomonosov nomli Nozik kimyo texnologiyasi instituti xodimlari ham jalb qilinishi bejiz emas edi. Bu borada professor K.Axmerov, professor D.Yusupov, dosent K.Xidoyatov va boshqalarning xizmati katta boʻldi. Natijada Novgorod «Azot» korxonasida piridin asoslari ishlab chiqariladigan 5 tonnalik reaktor qurib ishga tushirildi, sinovlar oʻtkazildi. £ - pikolin va boshqa mahsulotlar sintezi muvaffaqiyatli amalga oshirildi.\n" +
            "Joiz boʻlganda bir tarixiy voqeani eslatib oʻtishni lozim topamiz. K.Axmerovning ilmiy faoliyatiga tegishli ushbu voqea 1981 yilning 23 martida, ya'ni olimning doktorlik dissertasiyasi yoqlagan kunda boshlandi. Maxsuslashtirilgan ilmiy kengash soʻnggida a'zolar bir ovozdan dissertantning Chichibabin reaksiyasini mukammal oʻrganish,  uni keng koʻlamda tadqiq qilib, kattagina yangi katalizatorlar taklif qilganligi, reaksiya kinetikasini chuqur tahlil bilan hal qilgani, oʻrganilgan koʻpgina yoʻnalishlarning amaliy jihati, ekologik muammolar hisobga olinganligi, ilmiy ma'lumotlarning monografiya, darslik va oʻquv qoʻllanmalarda yoritilishi, mualliflik guvohnomasi va patentlarga kiritishini hisobga olib, ushbu reaksiyani bundan buyon «Chichibabin - Axmerov» reaksiyasi deb atashni qabul qilib, protokolga kiritilganligini eslatib oʻtamiz. Oʻsha taklifga ahamiyat bermaganligi, bir tomondan, oʻzbek olimining kamtarligini koʻrsatsa, ikkinchi tomondan, vatandoshimizning nomi nomdor reaksiyalar qatoriga kirib qolishi joiz boʻlar edi, degan oʻyga boramiz. Shunga qaramay, olimning qilgan ishlari, pedagogik faoliyati, «ustoz-shogird» tizimiga qoʻshib kelayotgan hissasi va jamoat ishlari uning olgan mukofotlari zamirida xalqimiz orasidagi obroʻ-e'tibordan darak berib turibdi. Ustoz domlaning talabalar, magistrlar, aspirant va doktorantlar orasidagi faol mehnati, yozgan darsliklari, oʻquv qoʻllanmalari, «Fan va turmush». «Ximiya i jizn» kabi va boshqa jurnallardagi ilmiy-ommabop maqolalari koʻpchilikning diqqat-e'tiborini oʻziga tortadi. Domla bilan koʻrishib, u kishining dilrabo soʻzlari, ularning maslahatlarini tinglash, istagan savolingizga qoniqarli javob olishingiz kishiga zavq\n" +
            "bagʻishlaydi. Olim ishlab turgan Toshkent Kimyo-texnologiya instituti jamoasi ham oʻzining yarim asrdan ortiq umrini yosh kadrlarni tayyorlashga bagʻishlagan pedagogini hurmatlab, ezozlashini hamma biladi. Biz ham Kudrat hoji Axmerov koʻp yillar davomida navqiron holda oramizda faoliyat koʻrsatib, barchamizga quvonch bagʻishlab yurishlarini tilab qolamiz.\n"
    },
    {
        id:'6',
        img: img6,
        fullName: "Soyibjon Sodikovich Negmatov ",
        text: "Oʻzbekiston Respublikasi Fanlar akademiyasining akademigi, texnika fanlari doktori, professor Soyibjon Sodikovich Negmatov 1941 yil 16 aprelda Andijon shahrida tavallud topdi.\n" +
            "1965 yili Toshkent Politexnika institutini (hozirda Islom Karimov nomidagi Toshkent Davlat texnika universiteti)ni bitirib,  1969 yili polimer qoplamalar olish texnologiyasi va ularning uzoq muddatga chidamliligi muammolari echimiga bagʻishlangan nomzodlik dissertasiyasini himoya qildi. 1980 yili Moskvada SSSR FAning Kimyoviy fizika instituti huzuridagi ixtisoslashgan kengashda «Paxta yigʻim-terimi va qayta ishlash mashina va mexanizmlari uchun polimer kompozision qoplamalarni tadqiq etish va ularni olish texnologik jarayonini yaratish» mavzusidagi doktorlik dissertasiyasini himoya qildi. 1984 yildan Yuqori mustahkam polimer tizimlar fizikasi kafedrasi professori, 1986 yildan esa «Kompozision materiallar kimyosi va texnologiyasi» ixtisosligi boʻyicha professor. 1987 yilda Oʻzbekiston Respublikasi FAning muxbir a'zosi, 1994 yilda (noorganik kimyo yoʻnalishi boʻyicha) akademik etib saylangan. 1990 yili Xalqaro muhandislar akademiyasining muxbir a'zosi, 1996 yilda Xalqaro Oliy maktab akademiyasining akademigi etib saylangan.\n" +
            "S. Negmatov 1968 yildan 1978 yilgacha ToshPI va TAYIda assistent, dosent va kafedra mudiri lavozimlarida ishladi. 1978-1985 yillarda Oʻzbekiston Respublikasi Oliy va oʻrta maxsus ta'lim vazirining ilmiy ishlar boʻyicha oʻrinbosari lavozimida mehnat qildi. 1985 - 1992 yillarda «Kompozit» ilmiy-texnik markazning bosh direktori, Toshkent davlat texnika universiteti «Kompozision materiallar» ilmiy-tadqiqot boʻlimi mudiri sifatida faoliyat yuritdi. 1992-2004 yillarda Oliy va oʻrta maxsus ta'lim vazirligi tasarrufidagi «Fan va taraqqiyot» ilmiy-texnik majmuasi, keyinchalik 2004 yilda vazirlik tizimi qayta tashkillashtirilgandan keyin ToshDTU tasarrufidagi «Fan va taraqqiyot» ilmiy-texnologik majmuasi, 2007 yildan shu kungacha ToshDTU tasarrufidagi «Fan va taraqqiyot» davlat unitar korxonasi raisi lavozimida mehnat kilib kelmokla.\n" +
            "Akademik S. Negmatov kattik jismlar mexanokimyosi. kompozision materiallar kimyosi. fizikasi, mexanika va texnologiyasi sohalari boʻyicha yirik olim. Uning rahbarligi ostida olib borilayotgan fundamental tadqiqotlar kompozision materiallar kimyosi va texnologiyasi, fizik - kimyovny mexanika, kompozision materialshunoslik va nanokompozitlar doirasidagi istiqbolli va dolzarb muammolarni qamrab oladi.\n" +
            "S.Negmatov tomonidan funksional guruhlarning tabiatiga bogʻliq oʻzaro ta'sir darajasini yoritib beruvchn ion, kovalent va aralash turdagi dispers komponentli noorganik va organik matrisalarning mexanokimyoviy qattiq fazali oʻzaro ta'sirining umumlashtirilgan donor - akseptor (adgeziyali) modeli ishlab chiqildi va taklif etildi. Mineral va noorganik birikmalarni  aralashtirish jarayonidagi mexanik parchalanishga yoʻnaltirilgan kompozision materiallar mexanokimyoviy sintezining qonuniyatlari aniqlandi. Adgezion bogʻlanishlarni yaratish va ularning buzilishini oʻrganish asosida qattiq jismlarning adgezion oʻzaro ta'sirining molekulyar - mexano - elektrik nazariyasini ilgari surdi. Bu esa kompozision materiallarning yoʻnaltirilgan holda sintez qilinishiga imkon berdi.\n" +
            "Dispers toʻldiruvchili kompozitlarning qayishqoqligi va mustahkamligi nazariyasi doirasida S.Negmatov tomonidan inshootlardagi tebrannshni soʻndirish, tebranishga va issiqlikka bardoshliligini, elektroʻtkazuvchanligini oshirish boʻyicha tavsiyalar ishlab chiqildi. Bu oʻz navbatida aviasiya va radiotexnika sanoatida qoʻllaniladigan qator yuqori samarador maxsus yoʻnaltirilgan kompozision materiallarni yaratishga imkon berdi.\n" +
            "Soʻnggi yillarda S.Negmatov rahbarligida mahalliy va ikkilamchi xomashyolar asosida nanokompozision materiallarning yangi avlodini yaratish ustida ishlar olib borilmokda. Turli noorganik va organik kompozit tizimlarda nanotuzilish shakllanishi qonuniyatlari va mexanizmlarining tadqiq etilishi, ularning maqbullashtirilishi, sintez, tuzilishi, xossa hamda texnologik jarayonlar oʻrtasidagi bogʻliqlikning oʻrnatilishi zamonaviy jahon fanida katta ahamiyatga ega.\n" +
            "Metallar va ularning eritmalarini korroziyadan himoyalovchi kompozitlar va usullarini yaratish boʻyicha olib borilgan izlanishlar S.Negmatovning ilmiy faoliyatida alohida oʻrin egallaydi. U tomonidan korroziyabardosh himoyalovchi kompozision polimer qoplamalar yaratilgan boʻlib, oltin va neft qazib olishda, kon boyitish korxonalarida hamda avtomobilsozlikda texnologik uskunalarni himoyalashda keng qoʻllanilmokda.\n" +
            "Fundamental tadqiqotlar natijasida mahalliy mineral xomashyolar (vollastonit, kaolin, qoʻngʻ. bentonit, dala shpati, kvars) va ishlab chiqarish chiqindilarini (fosfogips, toshqollar, qurum va boshqalar) boyitish va faollashtirishning istiqbolli ekologik toza texnologiyalari yaratilib, buning natijasida mahsulotni toza va yuqori tarkibli boʻlishiga erishiladi. Bu oʻz navbatida noyob va qimmatbaho materiallar xarajatini kamaytirib, foydalanish umli masalasini echadi xamda texnik va maishiy maxsulotlarni ishlab chikarish uchu n omilkor chikigsiz texnologiyalar yaraippga olib kelali.\n" +
            "S.Negmatovning «Kompozision polimer materiallarning tolasimon modda bilan bogʻliq oʻzaro ta'sir asoslari» monografiyasida ishqalanish va eyilishda kompozision materiallarning oʻzaro ta'sir mexanikasi, ishqalanish doirasida materiallarning deformasiyalanishi va mustahkamligi boʻyicha koʻp yillik izlanishlarning natijalari keltirilgan. Yangi kompozision polimer materiallar va mahsulotlarni, ularni olish texnologiyasini ishlab chiqish akademik S.Negmatov rahbarligi ostida olib borilayotgan fundamental va ilmiy-uslubiy izlanishlarning mantiqiy davomi boʻlib kelmoqda.\n" +
            "Tebranishdan himoyalovchi va zararni kamaytiruvchi yuqori samarador kompozision polimer materiallarni nozik inshootlarda qoʻllash ularning tebranishga mustahkamligining va ishlash muddatining uzaytirilishiga olib keladi. Paxta majmuasidagi mashina va mexanizmlarning ishchi organlari uchun kompozision polimer materiallarni ishlab chiqish va ularni joriy etish texnik - iqtisodiy va agrotexnik koʻrsatkichlarini yaxshilashga, tola va urugʻlar zararlanishining pasayishiga (2 - 2;5 marotaba), mashinalarning ishlab chiqarish koʻrsatkichlarini oshirishga (15 - 20%), quvvat xarajatini kamaytirishga (20 - 30%), tola chiqish koʻrsatkichini koʻpaytirishga (1% gacha), metall sarfini sezilarli darajada cheklanishga va shu jumladan, mashinalarni yongʻindan saqlanishini ta'minlash va shovqin darajasining kamayishiga olib kelali.\n" +
            "S.Negmatov rahbarligi ostida ToshDTU «Fan va taraqqiyot» DUKda qator yillar davomida kompozision va germetik kompozision materiallar yaratish va ishlab chiqarish ustida muntazam ravishda tadqiqotlar olib borilmokda. Jumladan, ushbu yaratilgan mastikalar «Almati - Bishkek - Toshkent - Samarqand - Dushanbe» M - 39 magistral va «Fargʻona halqasi» M - 12 halqa yoʻllarida qoʻllanilgan. Asfalt-beton yoʻllar, koʻpriklar, aerodromlarni qoplash va deformasion yoriqlarni toʻldirish uchun yaratilgan kompozision polimer materiallar va mastikalar qoʻllanilganligi natijasida yoʻllardan foydalanish muddati joriy tamirlashlarsiz 2 - 2.5 barobar uzaytirildi va yoʻl qurilishida sarflanadigan mablagʻlarning tejalishiga olib keldi.\n" +
            "S.Negmatov rahbarligida neftgaz quvurlarini burgʻilashda qoʻllaniladigan burgʻilash eritmalari uchun mahalliy xomashyo va ishlab chiqarish chiqindilari asosidagi kompozision kimyoviy reagentlar yaratilganligini hamda ularning Andijon yogʻ-moy kombinatida sanoat miqyosida ishlab chiqarilishi tashkil etilganligini alohida ta'kidlash mumkin. Bundan tashqari, paxta, shoyi, jun, polimer va sintetik tolali toʻqimachilik materiallariga rang berish uchun boʻyovchi kompozisiya yaratish sohasiga salmoqli hissa qoʻshildi.\n" +
            "Dunyo amaliyotida birinchi boʻlib, rangli metallurgiyaning texnogen chiqindilaridan koʻpfazali kompozision materiallar asosida pirometallurgiya usulida mis olishning energiya va resurstejamkor ekologik toza chiqitsiz texnologiyasi ishlab chiqilib, bunda misni maksimal darajada ajratib olishga va toshqollarning sezilarli kambagʻallashishiga erishildi. Bu texnologiyaning Olmaliq togʻ - metallurgiya kombinatida 2013 yil may oyidan joriy etilishi yiliga qoʻshimcha 1428 t mis. 82 kg oltin va 4028 kg kumush olish imkoniyatini yaratdi va natijada iqtisodiy samaradorlik 20 mln. AKSh dollarini tashkil etadi.\n" +
            "S.Negmatov kompozision materiallar va texnologiyalar ilmiy maktabining asoschisi boʻlib, uning rahbarligida 16 nafar fan doktori va 60 dan ortiq fan nomzodlari tayyorlangan. U 20 ta monografiya, 800 dan ortiq ilmiy maqola, 70 ta ixtiro va patentlar muallifidir.\n" +
            "Akademikning faol ishtirokida 8 ta xalkaro va 10 ta respublika ilmiy simpoziumi va anjumanlar oʻtkazildi. Uning ilmiy izlanishlarining natijalari Rossiya, Ukraina, Belarus, Yaponiya, Fransiya, Avstriya, Italiya, Hindiston, Buyuk Britaniya, AQSh, GFR, Xitoy, Ispaniya, Bolgariya, Vengriya, Polsha, Ruminiya, Turkiya, Qozogʻiston, Qirgʻiziston, Tojikiston, Turkmaniston, Latviya va Estoniya davlatlarida oʻtkaznlgan xalqaro ilmiy anjumanlarda ma'ruza qilingan.\n" +
            "S. Negmatov Xalqaro mexanokimyoviy ilmiy assosiasiyasining ishqalanish, moylanish va eyilish, yangi materiallar va texnologiyalar boʻyicha MDN ilmiy kengashi a'zosidir. 1996 - 2012 yillar davomida fan doktori ilmiy darajasini beruvchi ToshDTU «Fan va tarakkiyot» D'-TS xuzuridagi D.067.50.01 - ixtisoslashgan kengashining raisi, OʻzR FAning Polimerlar kimyosi va fizikasn instituti huzuridagi D.015.24.01 - ixtisoslashgan kengashning a'zosi boʻlgan. 1999 yildan beri «Kompozision materiallar» Oʻzbekiston ilmiy-texnika jurnalining bosh muharriri. U «Xurmat belgisi», «Mehnat shuhrati» ordenlari va Oʻzbekiston Respublikasi Oliy Majlisining Faxriy yorligʻi bilan taqdirlangan.\n"
    },
    {
        id:'7',
        img: img7,
        fullName: "fullname",
        text: "text"
    },
    {
        id:'8',
        img: img8,
        fullName: "fullname",
        text: "text"
    },
    {
        id:'9',
        img: img9,
        fullName: "Xamdam Usmonovich Usmonov",
        text: "Xamdam Usmonovich Usmonov 1916 yil 16 oktyabrda Toshkent shahrida xunarmand oilasida tugʻilgan. Ota-onalari metallga ishlov berish ishlari bilan shugʻullangan. 1932 yilda X.Usmonov oʻrta maktabni tamomlab, Oʻrta Osiyo Davlat universitetiga oʻqishga kirgan va uni 1937 yilda a'lo baholarga bitirgan. X. Usmonovning mehnat faoliyati Kimyo fakultetida assistent lavozimida boshlangan va u bir vaqtning oʻzida aspiranturada ilmiy ishlarini ham olib borgan. \n" +
            "1941 yilda X. Usmonov nomzodlik dissertasiyasini himoya qilgan. 1941 yil avgustidan 1942 yil yanvarigacha Oʻrta Osiyo harbiy okrugining harbiy texnika oʻqishida kursant boʻlgan. 1942 - 1945 yillarda X.Usmonov Ikkinchi jahon urushida Evropa mamlakatlarini faishzmdan ozod qilishdagi janglarda qatnashgan. U Janubi- Gʻarbiy va 2-Ukraina frontlarida katta leytenant sifatida xizmat qilgan.\n" +
            "1946 yilda X. Usmonov universitetning Fizik kimyo kafedrasida dosent lavozimida mehnat faoliyatini davom ettirgan. U talabalarga fizik kimyo va kimyoviy termodi¬namika fanlaridan ma'ruzalar oʻqigan va Oʻzbekistonda ilk bor polimerlar kimyosi sohasida ilmiy izlanishlar olib borgan, bunda Fizik kimyo kafedrasi uchun an'anaviy boʻlgan termodinamik usullarni qoʻllagan.\n" +
            "1948 - 1951 yillarda X.Usmonov Moskvadagi Ya. Karpov nomidagi Fizik-kimyo institutida doktorant boʻlgan. X.Usmonovning ilmiy ishlari tabiiy va gidratsellyulozalarning strukturasini oʻrganishga va sellyulozaning biosintezi mexanizmini tadqiqot qilishga qaratilgan. X.Usmonov 1950 yilda Kimyo instituti qoshida mamlakatimizda birinchi marta tabiiy polimerlar ilmiy laboratoriyasini tashkil etib, shu laboratoriyaga raxbarlik qilgan. 1952 - 1956 yillarda Kimyo instituti direktori, 1956 - 1959 yillarda Oʻsimliklar kimyosi instituti direktori, 1959 - 1962 yillarda Tabiiy polimerlar laboratoriyasi kimyosi asosida yangi tashkil etilgan Polimerlar kimyosi institutida direktorlik lavozimida ishlagan. 1962 - 1963 yillarda Oʻzbekiston Fanlar akademiyasida akademik-sekretar lavozimida ishlagan.\n" +
            "1954 yilda X. Usmonov «Paxta va gidratsellyuloza tolalarining fizik-kimyoviy xossalaridagi farqning sabablari» mavzusida doktorlik diseertasiyasini yoqlagan.\n" +
            "1955 yili professor, 1956 yili Oʻzbekiston Fanlar akademiyasining muxbir a'zosi, 1966 yilda akademiyaning haqiqiy a'zosi etib saylangan.\n" +
            "Polimerlar kimyosi instituti 1963 yili Kimyo sanoatn vazirligiga tarmoq institut sifatida oʻtkazilgach, «Paxta sellyulozasining kimyosi va texnologiyasi ilmiy-tekshirish instituti» deb atala boshlagan. Institutga X.Usmonov 1982 yilgacha raxbarlik qilgan.\n" +
            "X. Usmonov paxta sellyulozasi kimyosi va texnologiyasi ilmiy-tekshirish institutida ishlab turgan vaqtlarida ilmiy ishlanmalarni sanoatga tatbiq qilishni tezlashtirish maqsadida institutning yangi binosini tajriba zavodi bilan Akademiklar shaharchasida tashkil qilgan. Bu institut 12 gektar maydonni egallagan boʻlib, 2 kavatli ma'muriy bino, 4 qavatli laboratoriya, 2 qavatli patent va standart laboratoriyalari uchun bino boʻlgan.\n" +
            "Tajriba zavodi institut hududining 80% ini egallagan boʻlib, quyidagi binolarda tsexlar joylashgan edi: sutkasiga 1000 kg paxta sellyulozasi ishlab chiqaradigan, 86 kishi ishlaydigan tsex; 4 kavatli binoda quyidagi tajriba qurilmalari joylashgan: asetilsellyuloza, triasetat tola, asetat tolani rasplav usulida oladigan, tibbiyot uchun polimer moddalar oladigan «Blyaks» qurilmasi, sirt-faol moddalar oladigan, asetatsellyuloza iplardan trikotaj mato tuqiydigan dastgoh, suyuq sovun oladigan va boshqa shu kabi tajriba mahsulotlari ishlab chiqaradigan tsex;\n" +
            "-\ttajriba oʻtkazish uchun kerakli issiq suv va bugʻ ishlab chiqaradigan qozonxona;\n" +
            "-\tmexanika tsexi;\n" +
            "-\tduradgorlik tsexi;\n" +
            "-\taseton va metilenxlorid moddalarini bugʻdan regenera¬siyalash tsexi;\n" +
            "-\treaktiv va material omborxonalari;\n" +
            "-\taylanma suvlarni sovutib beruvchi qurilma joylashgan bino;\n" +
            "-\tzavod ma'muriyati va oshxona joylashgan bino.\n" +
            "Institut eng yaxshi koʻrsatkichlar bilan ishlab turgan vaqtda xodimlarining soni 1100 ga etgan. Bularning koʻp qismi zavod ishchi va xizmatchilari boʻlgani uchun ularga maxsus yotoqxona qurilgan. Yotoqxona 1 pod'ezdli 9 qavatli boʻlib, hozirgi «Salom» choyxonasi yonida joylashgan.\n" +
            "Institut hududi 1995 yili Qurolli Kuchlar vazirligi tasarrufiga oʻtgan, institut xodimlari sohasiga yakin boʻlgan Fanlar akademiyasining boshqa kimyo institutlariga ishga yuborilgan.\n" +
            "X.Usmonov yosh kadrlarni tayyorlashga katta e'tibor qaratgan. Uning bevosita rahbarligida 11 nafar fan doktori va 120 dan ortik fan nomzodi tayyorlangan. Dissertasiyalar asosan paxta sellyulozasining kimyosi va fizikasi,   paxtachilik va paxta tozalash sanoati chiqindilarini kompleks qayta ishlash muammolari bilan bogʻliq boʻlgan. Paxta tolasini vegetasion davr davomida oʻrganish orqali sellyulozaning strukturasi, gʻoʻza rivojlanish vaqtidagi sellyuloza makromolekulalarining oʻlchamlari va sellyulozaning biosintezi haqida yangi ma'lumotlar olishga muvaffaq boʻlingan. Vegetasion davrda paxta tolasini elektronmikroskopik tadqiqotlari uni ustmolekulyar tuzilishi shakllanishining asosiy bosqichlarini aniqlashga imkoniyat bergan. \n" +
            "X Usmonov rahbarligida paxta tolasini fizik modifikasiyalash natijasida strukturaviy oʻzgarishlar tadqiq qilingan va bunday ta'sirlar sellyulozaning eterifikasiya va payvand sopolimerlash jarayonlaridagi reaksion faolligiga katta ta'sir qilishi aniqlangan. Sellyuloza ustmolekulyar tuzilishining turli kimyoviy qayta ishlashlar natijasidagi oʻzgarishlarining umumiy qonuniyatlari aniqlangan. Turli turdagi gidratsellyuloza tolalarining asosiy strukturaviy tavsiflari oʻrganilgan va tolalar ustmolekulyar tuzilishining genezisi bilan bogʻliq bulgan tadqiqotlar kaogulyasiya va plastifikasion chuzilishning strukturaga ta'siri tola olingan jarayonlarning turiga bogʻliqligi koʻrsatilgan. Bunday ma'lumotlar sun'iy tolalar ishlab chiqarish texnologiyasi uchun juda katta ahamiyatga ega boʻlgan.\n" +
            "X.Usmonov rahbarligida payvand sopolimerlar eritmalarining termodinamikasi va eruvchanligi boʻyicha fundamental tadqiqotlar oʻtkazilgan. Vinyuftorrining polimerlanish, sopolimerlanish va payvand polimerlanish reaksiyalaridagi reaksion qobiliyatini aniqlash boʻyicha chuqur izlanishlar oʻtkazilgan. Tabiiy va sintetik polimerlarning reaksion modifikasiyalashni sistematik oʻrganish ushbu jarayonlarning mexanizmini aniqlash imkoniyatlarini bergan va sintezning yangi usullari ishlab chiqilgan.\n" +
            "X.Usmonovning tibbiyotda va veterinariyada qoʻllaniladigan fiziologik faol polimerlarning sintezi va fizik-kimyoviy xossalarining tadqiqoti sohasidagi ilmiy izlanishlar polimerlar kimyosi, biologiya va tibbiyot uchun juda katta ahamiyatga ega.\n" +
            "Ilmiy ishlanmalar natijasida paxta sellyulozasidan sosiska va kolbasa qobigʻi, mikrokristall sellyuloza, bir necha turdagi tibbiyot preparatlari, asetat tolasining bir nechta yangi assortimenti, asetat tolalar ishlab chiqarish texnologiyasini takomillashtiradigan texnologik ishlanmalar ishlab chiqarishga tatbiq etilgan.\n" +
            "Dunyoning polimerlar kimyosi sohasi boʻyicha oʻtkazilgan koʻplab simpozium va konferensiyalarida X.Usmonov Oʻzbekiston olimlarining polimerlar kimyosi sohasidagi ilmiy yutuqlari toʻgʻrisidagi ma'ruzalari bilan qatnashgan. Bu yutuqlar dunyoda koʻzga koʻringan polimerlar kimyosi olimlaridan G. Mark va M. Gudman (AKSh). V.A. Kargin, Z.A. Rogovin, S.P. Papkov va P.V. Kozlov (Rossiya)lar tomonidan etirof etilgan. Yana Oʻzbekiston olimlarining kimyo fani boʻyicha erishgan yutuqlari hisobga olinib, 1978 yilda «Kimyo-78» simpoziumini Toshkent shahrida oʻtkazishga qaror qilingan.\n" +
            "Polimerlar kimyosi fani va texnikasi rivojiga qoʻshgan ilmiy ishlari hisobga olinib X.Usmonovga «Oʻzbekistonda xizmat koʻrsatgan fan va texnika arbobi» faxriy unvoni berilgan. Olim bundan tashqari 5 ta orden va 9 ta medal bilan mukofotlangan.\n" +
            "Shunday qilib, X.Usmonov Oʻzbekistonda polimerlar fanining asoschisi hisoblanadi. Uning yuqori molekulali birikmalarning kimyosi, texnologiyasi va fizik-kimyosi sohasidagi gʻoyalari hozirgi kunda ham juda dolzarb boʻlib, koʻpdan-koʻp shogirdlari tomonidan rivojlantirilmokda. Katta olim, fan tashkilotchisi, moxir pedagog va jamoat arbobi akademik Usmonov Xamdam Usmonovichning koʻp qirrali faoliyati xalqqa xizmat kilish uchun bagʻishlangan va barchamiz uchun oʻrnakdir.\n"
    },
    {
        id:'10',
        img: img10,
        fullName: "Mirxoji Askarovich Askarov",
        text: "Mirxoji Askarovich Askarov Toshkent shahrida 1931 yilning 30 aprelida dunyoga keldi. 1948 yilda 41- son oʻrta maktabni bitirib, shu yili Moskva Kimyo-texnologiya institutining charm va moʻyna mutaxassisligiga kirdi va uni 1953 yilda muvaffaqiyatli tamomladi. M. Askarov polimerlar kimyosining asoschilaridan biri Ivan Platonovich Losevga shogirdlikka tushdi. 1956 yil D.I. Mendeleev nomidagi Moskva Kimyo-texnologiya institutining plastmassalar texnologiyasi kafedrasi aspiranturasini tamomladi va ushbu institut qoshidagi ixtisoslashgan kengashda 1957 yilda «Arilalifatik poliamidlarning sintezini oʻrganish» mavzuida kimyo fanlari nomzodi ilmiy darajasini olish uchun dissertasiyani himoya qildi. \n" +
            "1967 yilda Oʻzbekiston Fanlar akademiyasining Oʻsimlik moddalari kimyosi ilmiy-tadqiqot institutida «Akril monomerlarining sopolimerlari sintezi va ularning xossalarini oʻrganish hamda ularni sellyulozaga tikish» mavzuida kimyo fanlari doktori ilmiy darajasini olish uchun dissertasiya himoya qildi. \n" +
            "1968 yilda «Yuqori molekulali birikmalar kimyosi» mutaxassisligi boʻyicha professor ilmiy darajasini oldi. Oʻz FAning muxbir a'zosi (1974). Oʻz FA ning haqiqiy a'zosi (2000). Avvaliga (1957 - 1958 yillar) Toshkent Politexnika institutinnng Organik kimyo kafedrasida assistent, katta oʻqituvchi lavozimlarida ishladi. 1959 - 1973 yillarda Polimerlar kimyosi institutida (avvalgi Paxta sellyulozasi kimyosi va texnologiyasi ilmiy - tadqiqot instituti) «Sellyuloza va uning murakkab efirlari» laboratoriyasi mudiri. \n" +
            "1973 - 1982 yillarda esa Oʻz FA Kimyo instituti direktori. 1983 - 1988 yillarda Toshkent Toʻqimachilik va engil sanoat institutining «Nazariy kimyo» kafedrasi mudiri: 1988 - 1993 yillarda Polimerlar kimyosi va fizikasi institutining direktori lavozimlarida ishladi. Hozirda Toshkent Toʻqimachilik va engil sanoat instituti «Kimyo» kafedrasining professori lavozimida ishlamokda. \n" +
            "M. Askarov fan olamida mustahkam oʻrnashib, mutaxassislar tayyorlash, shogirdlari bilan respublikada polimerlar kimyosi fanining rivojlanishiga oʻz ilmiy-tadqiqot ishlari bilan faoliyat koʻrsatdi. Polimerlar fanini jahon ilmi darajasida oʻstirib, unga hissa qoʻshish, fan nomzodlari va doktorlari tayyorlash, sanoatda ajoyib natijalarni joriy etish M.Askarovning asosiy faoliyati boʻlib qoldi. Uning chop etilgan ilmiy asarlari, monografiyalari, darsliklari, mualliflik guvoxnomalari hammasini tilga olish va sharxlash juda qiyin. Ammo ularni xulosalash sifatida olim tomonidan tayyorlangan 20 nafar fan doktori, 100 nafar fan nomzodi, yuzlab muhandislarning hozirda sanoat va fan dargohlarida ishlab turishi, 600 dan ortiq chop etilgan maqolalar, ularning orasida 115 dan ortiq mualliflik guvoxnomalari va patentlar hamda 20 ta monografiya va darsliklarni chop etgan. Jumladan, «Sintetik polimerlar kimyosi» (1965). «Polimerlar kimyosidan praktikum». «Polimerlar kimyosi» (1981). «Kimyo. Oliy ta'lim yurtlariga kiruvchilar uchun. Nazariy asoslar, namunaviy misol va masalalarning echilishi. Testlar» (2000), «Polimerlar kimyosi va fizikasi» (2004), «Polimerlar kimyosi va fizikasidan amaliy mashgʻulotlar» (2006) darsliklar. «Ionogen polimerlarni sintezlash», «Aminoalkilakrilatlarning polimerlanishi», «Itakonallarini sintezlash va polimerlash». «Kimyoviy faol polimerlar va oligomerlar» singari monografiyalarini eslatish kifoyadir.\n" +
            "M.Askarov oʻz oʻquvchilari va hamkasblari - A.Jalilov. B.Gʻofurov, P.Zokirov. N.Muxitdinova, A.Nazarov, Yu.Pogosov. B.Oyxujaev. I.Ismoilov. A.Alovitdinovlar bilan fanda ilmiy maktab yaratib, ulkan hissa qoʻshdi. M.Askarovning ilm sohasida oʻsishi uning betoʻxtov izlanishining samarasi boʻlsa kerak, zero, u shu vaqtgacha qilgan ishlarini etarli deb hisoblamagan. Olim izlanishlarini davom ettirib. respublika va xorijiy davlatlarda ma'ruzalar bilan anjuman hamda majlislarda qatnashdi. Jumladan, uning Angliyaning Manchester universitetida (1963 - 1964 yillar) stajyorlik. Amerika Qoʻshma Shtatlaridagi (1965. 1981) ma'ruzalari, binobarin. Miniapolis – Sentpol, Detroyt shaharlarining faxriy grajdani etib saylanishi, Fransiya, Gollandiya, Chexoslovakiya, Vengriya, Islandiya va Hindistondagi ma'ruza va suhbatlari olimning oʻz rejalarini sayyoramizning yuksak markazlari bilan solishtirib turishi, kezi kelganda u erlarga oʻz oʻquvchilarini yuborib turishi va ularni ham oʻz laboratoriyalarida ishlatib koʻrishini eng oliy ishlardan biri deb tushunadi.\n" +
            "1974 yilda delegasiyaga rahbarlik qilib, Ispaniyaning Madrid shahrida oʻtkazilgan IYuPAKning makromolekulyar kimyo Xalqaro simpoziumida qatnashdi va oʻzining ushbu simpoziumda orttirgan tajribalariga asoslangan holda 1978 yilda Toshkent shahrida oʻtkazilgan MAKPO-7S makromolekulyar kimyoning Xalqaro simpoziumida tashkiliy qoʻmita a'zosi sifatida faol ishtirok etgan.\n" +
            "1986 yilda Oʻzbekiston Respublikasi Fanlar akademiyasining kimyo -texnologiya fanlari boʻlimida rais oʻrinbosari lavozimiga tayinlandi.\n" +
            "1989 yilda Oʻzbekiston Respublikasi Fanlar akademiya¬sining yuqori molekulali birikmalar kimyosi ilmiy kengashining raisi etib tayinlandi.\n" +
            "M.Askarovning jamoat ishlarida ham xizmatlari beqiyos. U xali «Yosh kimyogar» akademiyasining rahbari, Butunittifoq kimyoviy olimpiadasining bosh hakami. «Fan va turmush», «Oʻzbek kimyo jurnali»ning xayat a'zosi, SSSR - AQSh doʻstlik jamiyatining raisi. Ammo har qancha tanish koʻp boʻlmasin, u har doim talaba va aspirantlarini oʻzining eng yaqinlari deb biladi va shu boisdan  qanchalik ishi koʻp boʻlmasin, Toshkent engil sanoat va toʻqimachilik instituti bilan doimiy hamkorlikda boʻladi.\n" +
            "M.Askarov yaratgan polimerlar kimyosi fizikasi va texnologiyasi sohasidagi ilmiy maktabi sergʻayrat, intiluvchan, unda kimyo fanini yangi choʻqqilarga chorlaydigan yosh olimlar bor.\n" +
            "M.Askarov sintetik polimerlarning olinishi va ularning plastmassalar sohasida qoʻllanishi borasida juda katta ilmiy ishlarni amalga oshirdi. Uning dastlabki izlanishlari aromatik diaminlarning atifatik ikki asosli kislotalar bilan polikondensatlanishi borasida boʻlib, natijada yuqori haroratga chidamli plastmassalar olish bilan yakunlangan. Uning ikkinchi bosqichidagi izlanishlari 50 dan ortik yangidan olingan monomerlarning polimerlanish kinetikasi va mexanizmini oʻrganishdan iborat boʻlib, karbozanjirli plastmassalarni barpo etishga qaratilgan, ularning xossalarini barqarorlashtirishga imkon beradi.\n" +
            "Hozirda M.A.Askarovning ilmiy yoʻnalishi tarkibila azot, kislorod va oltingugurt boʻlgan monomerlarni nisbatan past haroratda polimerlannshga, shu orqali plastmassalarning xossalarini yaxshilash va barqarorlashga qaratilgan. Uning ilmiy ishlari plastmassa buyumlarining yogʻ sanoatining qoldiqlaridan olinadigan barqaror izatorlarni keng koʻlamda qoʻllashga imkon berdi, puxtalangan polimer pardalar, linoleumlar ishlab chiqarish yoʻlga qoʻyildi. Shuningdek, tarkibila azot va kislorod saqlagan vinil monomerlarini (N-vinilsuksinimid. N - vinilpirrolidon, N-vinilkaprolaktam, akrilonitril, akril kislotasini) peroksid inisiatorlari va oʻzaro makromolekulalararo komplekslanish mahsulotlari bilan inisirlash orqali olish, plastmassalarni qayta ishlash jarayonlari polimerlarning molekulyar massasi taqsimlanishiga, oʻz navbatida uni polimerlarni sintezlash sharoitiga bogʻliqligidan foydalanishga bagʻishlangan ilmiy yoʻnalishda fundamental tadqiqot ishlarini oʻz shogirdlari bilan amalga oshirmoqda.\n" +
            "M.Askarov N-vinil va akro monomerlarini molekulalararo komplekslari yordamida almashinib keluvchi qoʻsh polimerlanish reaksiyasi mexanizmini yaratdi. Oqsil makromolekulasi ishtirokida oksidlanish - qaytarilish reaksiyasi orqali tabiiy ipakni N - vinilpirrolidonni payvand sopolimerlanishini amalga oshirdi. Payvand qilingan sopolimerlarni tabiiy ipakning boʻyalish xossalariga ta'siri oʻrganildi. Olingan natijalar Toshkent shahridagi «Tola» ochiq turdagi aksiyadorlik jamiyatida sinovdan oʻtkazildi.\n" +
            "M.Askarov Oʻzbekiston Oliy attestasiya komissiyasi rayosati a'zosi, ixtisoslashgan ilmiy kengashlar a'zosi. U kimyo fanini rivojlantirishdagi, yuqori malakali ilmiy kadrlar tayyorlashdagi munosib xizmatlari uchun ikki marta Oʻzbekiston Oliy Kengashining (1981. 1993) faxriy yorliqlari bilan mukofotlangan.\n"
    },
    {
        id:'11',
        img: img11,
        fullName: "Anna Ivanovna Glushenkova ",
        text: "Anna Ivanovna Glushenkova 1926 yilda Volgograd viloyatining Rudnyansk tumanida tavallud topgan. 1936 yilda otasining armiyadagi xizmatidan sung Surxondaryo viloyatining Termiz shahriga ota-onasi oilan koʻchib kelishadi. 1943 yilda Termizda oʻrta maktabni tamomlagach, Oʻrta Osiyo Industrial (soʻngra Toshkent Politexnika) institutiga oʻqishga kiradi. 1948 yilda institutni tamomlab, shu institutning aspiranturasida oʻqiydi.\n" +
            "1953 yilda professor A.L. Markman rahbarligi ostida «Paxta kunjarasnning yogʻligiga ayrim faktorlarning ta'siri» mavzuidagi nomzodlik dissertasiyasini himoya qiladi. Avval «Moylar texnologiyasi» kafedrasi dosenti, soʻngra mudiri lavozimlarida ishlab, Oʻzbekiston va xorijda yuqori malakali mutaxassislarning tarbiyasi va bilim olishiga sezilarli hissasini qoʻshgan. Talabalari orasida 3 nafar akademik - 3. S. Salimov, N.R.Yusupbekov va M.F.Abidova, yogʻ-moy kombinatlari direktorlari va boshka koʻzga koʻringan olimlar bor.\n" +
            "Kafedra mudirligi davrida Ittifoq oziq-ovqat sanoati vaziri P.V. Naumenko dan oʻz talabalarini Moskva, Leningrad, Krasnodar, Voronej, Xarkov, Poltava, Dnepropetrovsk va boshqa yirik shaharlardagi yogʻ-moy kombinatlarida diplomoldi amaliy ishlarini oʻtashi uchun ruxsatnoma olishga muvaffaq boʻldi. Buning natijasida talabalarning kungaboqar, soya, saflor kabi yogʻ manbalari boʻlgan oʻsimliklarni qayta ishlash tajribalarini oʻrganish va oʻsha davrda Oʻzbekistonda boʻlmagan fosfolipidlar, gliserin ajratib olish, gidrogenizasiya, pereeterifikasiya texnologiyalari bilan tanishish imkoni yaratildi. Bundan tashqari, talabalarning Ittifoqning markaziy shaharlarida boʻlishi ularning umumilmiy saviyasi oʻsishiga olib keldi.\n" +
            "1961 yildan boshlab A. I. Glushenkova Oʻz FA UMKI da avval katta ilmiy xodim, soʻngra lipidlar kimyosi laboratoriyasi mudiri, 1984 yildan to 1989 yilgacha ushbu institutning direktori lavozimida ishlab keldi.\n" +
            "1972 yilda Gidrogenizatlar tarkibiga katalizator tabiatining va paxta yogʻining gidrolash rejimlari ta'siri» mavzuida doktorlik dissertasiyasini himoya qilib, 1982 yilda professor unvoniga sazovor boʻlib, 1984 yilda Oʻz FA muxbir a'zosi, 1989 - 1991 yillar FA Prezidiumi a'zosi, 2000 yildan esa OʻzR FA akademigi unvoniga erishdi.\n" +
            "A.I.Glushenkova - tabiiy birikmalar kimyosi va texnologiyasi sohasida taniqli olima. Butun umrini va ilmiy faoliyatini lipidlar, xususan paxta texnologiyasi va kimyosi bilan bogʻladi.\n" +
            "Namangan shahridagi zavodda tadqikotini olib borgan fan nomzodligi ishida eksperimentlar natijatarini qayta ishlash uchun matematik statistika usulini qoʻllagan. Bu oʻz navbatida turli namlik, harorat, muzlatish va maydalanish darajalari koʻrsatkichlarida paxta gʻoʻzasini mexanik presslarda presslashning asosiy parametrlarini aniqlab chiqishga olib keldi. Bunday yondashish natijasida kunjara yogʻligini kamaytirish hisobiga yogʻni koʻproq olish imkonini yaratgan. Oʻz vaqtida zamonaviy sanalgan superduoekspeller apparatlarida paxta chigitini qayta ishlashning optimal shart-sharoitlarini ishlab chiqishga muvaffaq boʻlindi. Nomzodlik ishining natijalaridan respublikaning yogʻ-moy kombinatlarida foydalanib, gʻoʻzaning dastlabki presslanishini qoʻllab, olishning noekstraksion usuliga oʻtib ketildi.\n" +
            "A. I. Glushenkovaning 1952 yilda chop etilgan dastlabki ishida  paxta yogʻi sifatini oshirish uchun uni oqartirishda mahalliy tuproqlardan foydalanish imkoniyatlari koʻrsatib oʻtilgan edi. Olima alohida e'tiborini gossipoli kam boʻlgan yogʻ va shrot olish hamda paxta yogʻini gidrogenizasiya jarayonini oʻrganishga qaratgan edi.\n" +
            "Gossipolsiz yogʻ va shrotni olish maqsadida A. I. Glushenkova hamkasblari bilan birgalikda chigit myatkasidan avval geksan bilan yogʻlarni, soʻng suvli aseton bilan gossipolni ajratib olish usulini tavsiya qildi. Natijada, nafaqat gossipolsiz yogʻ va shrot olinishiga, balki qoʻshimcha mahsulot sifatida, qator tibbiy preparatlarni yaratishda ishlatiladigan gossipol ham ajratib olinishiga erishildi.\n" +
            "Olima amaliyot masalalari bilan birga fundamental muammolarga ham katta e'tibor qaratgan. Hamkasblari bilan birgalikda gossipol kimyosini oʻrganish vaqtida uning molekulasi komplanar emasligini isbotladi hamda natriy gidroksid bilan faqat 1.1 - holatidagi gidroksil guruhlar reaksiyaga kirishishi muammosiga oydinlik kiritdi.\n" +
            "A. I. Glushenkova bundan tashqari hamkasblari bilan gossipolning quyimolekulali spirtlarda oʻzini tutishini oʻrganib chiqdi va kimyoviy, fizik-kimyoviy usullardan foydalanib, gossipolni metanol bilan ta'sirlashishi natijasida mono- va di- asetallar hosil boʻlishini koʻrsatdi.\n" +
            "Paxta yogʻi boʻyicha tadqiqotini davom ettirganda. A. I. Glushenkova hamkasblari bilan birgalikda uni gidrogenlashning quyi haroratli rejimini ishlab chiqdi. Buning uchun avval qaytarilgan, metallar nisbati 1:1 boʻlgan mis - nikelli katalizatordan foydalandi. Bunday texnologiya gidrogenizat sifatini oshirib, trans - kislotalar miqdorining kamayishi, yogʻ va katalizator yoʻqotilishining kamayishiga olib keldi. A. I. Glushenkova tarkibida metallarni turli nisbatli dispers mis - nikelli katalizatorlar triasilgliserinlar molekulasidagi asillarni trans - izomerizasiyasiga turlicha ta'sir qilishini va \n" +
            "katalizator faolligi uning selektivligiga teskari proporsional ekanligini koʻrsatib oʻtdi. Bu usul Toshkent yog-moy kombinatida tatbiq qilinib, yuqori iqtisodiy samaradorlikka erishildi.\n" +
            "Usimlik yogʻlari gidrogenizasiyasi jarayoni mexanizmi haqidagi tadqiqotlarini ketma-ketlik bilan rivojlantirib A. I. Glushenkova ushbu jarayonda triasilgliserinli izomerizasiya mavjudligini belgilab, toʻyinmagan moy kislotalarining pozisnon izomerizasiyasida qoʻshbogʻlarning ham metil, ham karboksil guruhga nisbatan bitta metilen guruhga siljishi hamda qoʻshbogʻlarning gidrolanish tezligini ularning karboksil guruhdan uzoqlanishiga bogʻliq ravishda ortishini aniqladi. Ushbu ishlar gidrogenizasiya jarayonida qoʻshbogʻlar birikkan sistemali kislotalarning hosil boʻlishini tushuntirib berishga imkon berdi. Moylarning toʻyinmaganlik darajasini aniqlash uchun original usulni topdi. Avval foydalanilgan yodli raqam oʻrniga yuzta moy kislotalaridagi qoʻshbogʻlarning umumiy sonini koʻrsatuvchi «toʻyinmaganlik raqami» koʻrsatkichidan foydala- nishni tavsiya qildi:\n" +
            "T.R.= 1∑N'+2∑N\"+3∑N\"'-...5\n" +
            "bu erda: N', N\". N''' - aralashmaning tarkibidagi kislotalar yigʻindisining yuzta molekulasidagi monoen, dien va trien kislotlarining molekulalari soni;\n" +
            "1.2.3- kislota molekulasidagi qoʻshbogʻlar soni.\n" +
            "Ushbu koʻrsatkichning ustuvorligi moy kislotalarining molekulyar massasi, uning molekulasidagi etilen bogʻlarning joylashuvi va konfigurasiya kabi koʻrsatkichlardan mustaqil ekanligida.\n" +
            "Yogʻlar, moylar va qoʻshimcha lipofil birikmalar analizining usullarini takomillashtirib A. II. Glushenkova hamkasblari bilan birgalikda quyimolekulyar moy kislotalari va gossipurpurinning gossipolli aralashmasidagi miqdorini aniqlash usullarini ishlab chiqdi.\n" +
            "A.I.Glushenkovaning qator ilmiy ishlari yovvoyi va madaniylashtirilgan dorivor oʻsimliklarning lipidlar tarkibi, tuzilishini, funksiyasini oʻrganishga bagʻishlangan. Uning hamkasblari bilan yovvoyi holda oʻsuvchi dorivor oʻsimliklarning lipidlari boʻyicha olib borgan fundamental tadqiqotlari moy kislotalari tarkibining xemotaksonomik ahamiyati va yuqori oʻsimliklarning namlangan lipidlari triasilgliseridlari tuzilishini aniqlashga imkon berdi.\n" +
            "Paxtaning vilt bilan kasallangandagi chigitining lipidlari oʻzgarishlarini oʻrganish paxtaning zamburugʻli infeksiyalarga chidamlilik mexanizmini aniqlashga imkon berdi hamda ushbu kasallikka qarshi kurashish yoʻllarini tugʻri moʻljallashga olib keldi.\n" +
            "A. I. Glushenkova oʻz ishlarida hamkasblari bilan lipidlar analizi uchun zamonaviy fizik va kimyoviy usullar kompleksidan keng foydalanib, triasilgliperollar, moy kislotalari tarkibi va tuzilishi, paxta chigitida triasilgliserollarning biosintezi yoʻllari va moylar qayta eterifikasiyalanishi hakida yanada toʻlaroq ma'lumotlarga ega boʻlindi.\n" +
            "Kanop fosfolipidlarini oʻrganish davrida A I. Glushenkova, X.S. Muxamedova rahbarligidagi bir guruh olimlar tarkibida yuqori oʻsimliklar uchun fosfolipidlarning yangi sinfini - dengiz hayvonlari uchun xos boʻlgan fosfonolipidlarni birinchi marta aniqlashdi. Bundan tashqari fosfonolipidlarni fosfolipidlardan ajratib olish usuli ishlab chiqildi, birinchi marta\tfosfonofosfatidil etanolaminlarining tuzilishi aniqlandi.\n" +
            "Hippophae rhanmoides urugʻlari lipidlarini tadqiq etishda A. I. Glushenkova, Ya.V. Rashkes va boshqalar avval urugʻlarning liganlari tarkibida aniqlanmagan yangi kislotalarni aniqlashga muvaffak boʻlishdi. Ularga 11 - gidroksi - 9 - tridesen. 9 - gidroksi - 10.12 - pentadekadien. 13 - gidroksi -9.11 - geksadedien va 9.12 - digidroksi - 15 - nonadepen kislotalari kiradi.\n" +
            "\n" +
            "СН3СН2СН(ОН)СН=СН(СН2)7СООН\n" +
            "11\t- gidroksi - 9 - 13:1 \n" +
            "СН3СН2СН=СНСН=СНСН(ОН)(СН2)-СООН \n" +
            "9 - gidroksi – 10,12 - 15:2 \n" +
            "СН3(СН2)2СН(ОН)СН=СНСН=СН(СН2)7СООН \n" +
            "13 - gidroksi -9,11 - 16:2\n" +
            "СН3(СН2)2СН=СН(СН2)2СН(ОН)(СН2)2СН(ОН)(СН2)7СООН \n" +
            "9.12- digidroksi-- 15 - 19:1\n" +
            "Kastor moyining oksidlangan triasilgliserinlarini va ularning trimetilsilil hosilalarini oʻrganishda mas spektrometrik fragmentasiyadan foydalanshp oksidlangan triasilgliserinlar aralashmasining analizida ushbu usul qoʻl kelishini koʻrsatdi.\n" +
            "Galeopsis bifida urugʻlari lipidlarini oʻrganishda A. I. Glushenkova va hammualliflari birinchi marta oltita yangi kislotani aniqlashdi va ularning tuzilishini belgilashdi: sis – 10,11 - epoksi - sis - 7 - 16:1, sis – 13,14 - epoksi – sis, sis – 7,10 - 16:2,  trans - 15,16 - epoksi – sis, sis – 9,12 - 18:2, sis - 15.16 - epoksi – sis, trans(trans, sis) – 9,12 - 18:2, sis – 11,12 - epoksi - sis - 14 - 20:1 va sis – 17,18 – epoksi, sis, sis – 11,14 - 20:2.\n" +
            "\n" +
            "CH3(CH2)4CHOCHCH2CH=(CH2)5COOH\n" +
            "\n" +
            "sis – 10,11 - epoksi - sis - 7 - 16:1 \n" +
            "CH3CH2CHOCHCH2CH=CHCH2CH=CH(CH2)7COOH\n" +
            "\n" +
            "sis – 15,16 - epoksi – sis, trans(trans, sis) – 9,12 - 18:2\n" +
            "Acanthopanax sessiflorus mevalarining lipidlarida yangi 6 ta gidroksikislota aniqlandi va ularning tuzilishi belgilandi: 6 - gidroksigeksadeka - 12 - sis – en, 6 - gidroksigeksadeka - 9 – sis, 12\n" +
            "\n" +
            "-\tsisdien, 6(7) - gidroksioktadeka - 12 - sis – en va 6(7) - gidroksioktadeka - 9 – sis, 12 - sis - dien kislotalarining izomerlari.\n" +
            "\n" +
            "CH3(CH2)2CH=CH(CH2)5CH(ОН)(CH2)4COOH\n" +
            "-\t6 - gidroksi - sis - 12 - 16:1\n" +
            "\n" +
            "CH3(CH2)2CH=CHCH2CH=CH(CH2)2CH(ОН)(CH2)4COOH\n" +
            "\n" +
            "-\t6 - gidroksi - sis; sis - 9.12 - 16:2\n" +
            "     Eleagnus angustifolia urugʻlari lipidlarida yangi 12 - gidroksi—\t8.10 — oktadekadien kislota aniqlandi.\n" +
            "\n" +
            "CH3(CH2)5CH(ОН)(CH=CH)2(CH2)6COOH\n" +
            "-\t12\t- gidroksi - 8.10 - 18:2\n" +
            "              A. I. Glushenkovaning qator ishlari farmasevtika, oziq - ovqat va qishloq xoʻjalik chiqindilaridagi lipidlarni oʻrganishga bagʻishlangan. Hamkasblari bilan birgalikda kartoshka er ustki qismining lipidlari asosida yaralarni bitkazuvchi «Lipozol» vositasi ishlab chiqildi. Farmasevtik ishlab chiqarish chiqindilarining lipidlarini oʻrganish bilan ularni kundalik  kimyo va kosmetik vositalar ishlab chiqish uchun istiqbolliligi koʻrsatilib, soʻngra ayrimlari ishlab chiqarishga tatbiq qilindi.\n" +
            "Paxta yogʻini rafinasiya qilish jarayonida qoladigan chiqindi - soapstokdan moy kislotalari ajratib olingan va etilenglikol bilan eterifikasiyalantirib, hosil boʻlgan mahsulot Toshkent goʻsht kombnnatida terilarni moylashda ishlatildi.\n" +
            "A. I. Glushenkovaning lipidlar kimyosi va texnologiyasi sohasidagi 38 ishi Ipifok va Oʻzbekiston Respublikasining mualliflik guvoxnomalari va patentlar bilan tasdiqlangan. Uning va hamkasblarining ijodiy izlanishlari natijalari «Moylar gidrogenizasiyasi» («Gidrogenizasiya jirov»). «Gossipol, uning hosilalari va ulardan foydalanish» («Gossipol, ego proizvodnie i ix ispolzovanie») kabi monografiyalarda, respublikamiz va chet el jurnallarida, ishtirok etgan hamda nutq soʻzlagan respublika va xalqaro ilmiy konferensiyalar, simpoziumlar, kongresslar toʻplamlarida chop etilgan 400 dan ortiq ilmiy nashrlarida umumlashtirilgan.\n" +
            "Anna Ivanovna kadrlar tayyorlashga katta ahamiyat berib, uning rahbarligi ostida 1 ta fan doktori, 12 nafar fan nomzodi oʻz dissertasiya ishlarini himoya qilishgan. OʻzR FA Oʻsimlik moddalari kimyosi institutida ishlab turib shu vaqtda Toshkent Kimyo-texnologiya institutining «Moylar texnologiyasi» kafedrasida hamda Buxoro Ozik-ovqat va engil sanoat institutlarida maxsus kurs va birinchi marta tatbiq etilgan fan - talabalarning ilmiy ishlari asoslaridan ma'ruza oʻqib keldi.\n" +
            "A. I. Glushenkova katta jamoatchilik ishlarini olib boradi. U AQShda ingliz tiliga tarjima qilinadigan «Ximiya prirodnix soedineniy» jurnali bosh muharririning oʻrinbosari vazifasini bajarib kelgan. Oʻz davrida bioorganik kimyo, tabiiy va fiziologik faol birikmalar boʻyicha Muammoli Kengash raisi, OʻMKI qoshidagi ilmiy seminar raisi va Bioorganik kimyo instituti qoshidagi ilmiy seminar a'zosi hamda OAK ekspert komissiyasining a'zosi boʻlgan. Turli davrda «Oʻzbek kimyo jurna¬li» xayati a'zosi, Beruniy nomidagi Davlat mukofotlarini berish qoʻmitasining ilmiy kotibi, Ittifok Lenin va Davlat mukofotlarini berish boʻyicha kimyo seksiyasining Sankt- Peterburgdagi moylar boʻyicha doktorlik dissertasiyalarini himoya etish boʻyicha Ixtisoslashtirilgan Kengashning OʻzR FA UMKI va Toshkent Kimyo-texnologiya instituti qoshlaridagi Ixtisoslashtirilgan Kengashlarning a'zosi boʻlib kelgan. Bundan tashqari, Anna Ivanovna Glushenkova «Olima» ilmiy jamiyatining tashkilotchilaridan biri boʻlib, uzoq vaqt ushbu jamiyatning a'zosi boʻlib kelgan.\n" +
            "A. I. Glushenkovaga katta talabchanlik va mehnatga layoqati bilan birga asosiy yoʻnalishlarni koʻra bilish va xalq xoʻjaligi uchun muhim izlanishlar olib borish qobiliyati, topshirilgan majburiyatlarga mas'uliyati, koʻnikma va bilimlari bilan yoshlarga ulashishga shayligi, ezgulik va kuyinchaklik xosdir. Uning ilmiy va jamoatchilik faoliyati qator davlat mukofotlari bilan belgilangan. Ular orasida «Xalqlar Doʻstligi» va «Mehnat shuhrati» ordenlari hamda «Shavkatli mehnati uchun» medali bor. Bulardan tashqari, «Oʻzbekistonda xizmat koʻrsatgan fan arbobi» faxriy unvoniga sazovor boʻlgan.\n"
    },
    {
        id:'12',
        img: img12,
        fullName: "Sadriddin Muhamaddinovich Turobjonov",
        text: "Professor S.Turobjonovning ilmiy-amaliy tadqiqotlari asosiy (ogʻir) organik sintezi texnologiyalarini chuqur oʻrganish, rivojlantirish va sanoatga joriy qilish maqsadida mahalliy xom ashyolar va sanoat chiqindilari asosida piridinlar, aseton va murrakab efirlar, korroziya va mineral tuzlar toʻplanishiga qarshi ingibitorlarini olish texnologiyalarini yaratishga bagʻishlanib, bu sohada katta ilmiy maktab yaratilgan. \n" +
            "S. Turobjonov va uning ilmiy maktabining, ilmiy tadqiqotlarining asosiy nazariy va amaliy natijalari quyidagilardan iborat:\n" +
            "-mahalliy xom ashyolar asosida piridinlar, aseton, murakkab efirlar va korroziya ingibitorlari olishning bir bosqichli, kam chiqindili texnologiyalari yaratilgan;\n" +
            "-piridinlar va ularning metil gomologlari asetilen qator, etilen qator va karbonil birikmalarning ammiak va aminlar asosidagi oʻzaro katalitik jarayonlari chuqur nazariy va amaliy oʻrganilgan. Birinchi marta qimmatli xom ashyo asetilen oʻrniga “Navoiazot” AJ ikkilamchi hom ashyosi asetilen saqlovchi chiqindi gazlarni piridinlar sintezida ishlatilishi mumkinligi koʻrsatilgan;\n" +
            "-asetilen va ammiak asosida 2- va 4- metilpiridinlar sintezi uchun yangi alyuminiy ftoridli modifikasiyalangan KSXA (kadmiyruxxromalyuminiy) va SXA (ruxxromalyuminiy) hamda JSXA (temirruxxromalyuminiy) tarkibli yuqori samarali,  koʻp fuksiyali katalizatorlar yaratilgan. Tajriba, sanoat qurilmalarida ularni uzoq vaqt, doimiy faollikda va past haroratda 1200 soatdan ortiq ishlashi koʻrsatilgan;\n" +
            "-birinchi marotaba “Navoiazot” AJ chiqindisi kroton fraksiyasi va ammiakning kondensatlanishi  orqali korroziyaga qarshi ingibitorlar texnologiyasi yaratilgan va ishlab chiqarishga joriy etilgan. Shuningdek biokimyoviy ishlab chiqarish korxonalari chiqindisi efiraldegid fraksiyasi (EAF) va sivush moylarini qayta ishlash texnologiyasi yaratilib “Azot” AJ (Fargʻona sh.)  ishlab chiqarishga joriy qilingan.\n" +
            "Qayd etilgan ilmiy-tadqiqot ishlarning dolbzarligi ilmiy va amaliy jihatdan asoslangan boʻlib, respublikada asosiy (ogʻir) organik sintez mahsulotlari texnologiyalari chuqur oʻrganilgan, katalitik geterosikllash jarayonlarida reagentlarni faollashtirish nazariyasi rivojlantirilgan, maxalliy hom ashyolari va sanoat chiqindilari asosida yangi maxsulotlar sintezi texnologiyalari yaratilgan hamda sanoatga tatbiq etilgan. \n" +
            "S. Turobjonov oʻz ilmiy maktabini yaratish bilan bir qatorda, yuqori malakali ilmiy-pedagogik kadrlar tayyorlashga alohida e'tibor qaratgan. Uning ilmiy rahbarligida va maslahatchiligida 29 ta nomzodlik va 7 ta doktorlik dissertasiyalari himoya qilingan. U kimyo sohasidagi olim sifatida, 17 dan ortiq patent, 300 dan ortiq ilmiy maqola, 14 ta darslik va  oʻquv qoʻllanmalari, 8 ta xalqaro monografiya hamda 20 dan ortiq oʻquv-uslubiy ishlanmalar muallifidir.\n" +
            "S.Turobjonov Oʻzbekiston Respublikasi Prezidentining farmoniga binoan “Doʻstlik” ordeni bilan taqdirlangan. \n" +
            "S.Turobjonov Oʻzbekgidroenergo aksiyadorlik jamiyatinig “Gidroenergetika iftixori” koʻkrak nishoni bilan taqdirlangan. \n" +
            "S.Turobjonov Toshkent kimyo texnologiya instituti huzuridagi fan doktori ilmiy darajasini beruvchi DSc.27.06.2017.T.04.01 raqamli Ilmiy Kengashi raisi. Oliy maktablar xalqaro Fanlar Akademiyasining (haqiqiy a'zosi) akademigi (Rossiya) hamda “Kimyo texnologiyalar” xalqaro jurnalining (Rossiya, Moskva) tahririyat a'zosi. \n" +
            "Qozogʻiston Respublikasi Xalqlar doʻstligi universitetining (2015 yil),  Belarus milliy texnika universiteti (2020 yil), Rossiya Federasiyasining «Moskva energetika instituti” milliy tadqiqot universiteti (2022 yil), Tojikiston Respublikasi “Texnologiyalar va innovasion menejment” instituti (2022 yil),  “Faxriy professori”, Belarus davlat texnologiyalar universiteti (2021 yil), Sankt-Peterburg politexnika universiteti (2023 yil) va Nijniy Novgorod texnika universiteti (2024 yil) “Faxriy doktori” hisoblanadi.\n"
    },
    {
        id:'13',
        img: img13,
        fullName: "Gʻaffor Raxmonberdievich Raxmonberdiev",
        text: "Qozogʻiston Respublikasi Fanlar akademiyasining akademigi, kimyo fanlari doktori, professor Gʻaffor Raxmonberdievich Raxmonberdiev 1938 yil 16 mayda Toshkent shahrida xizmatchi oilasida tavallud topdi. 1957 yili oʻrta maktabni medal bilan bitirgandan soʻng Toshkent politexnika institutining kimyo-texnologiya fakultetiga oʻqishga kiradi va uni 1962 yili muvaffaqiyatli bitiradi. Unga kimyogar-texnolog mutaxassisligi beriladi.\n" +
            "Institutni bitirgandan soʻng Gʻ.Raxmonberdiev Sankt- Peterburg shahridagi Rossiya FAga qarashli Yuqori molekulali birikmalar instituti aspiranturasiga kiradi. U sellyuloza kimyosi sohasida taniqli olimlar Rossiya FAning muxbir a'zosi N.I.Nikitin, professor G.A.Petropavlovskiy laboratoriyasida saboq oladi. 1968 yilda Sankt-Peterburg shahrida nomzodlik diseertasiyasini himoya qilgandan soʻng Ittifoq kimyo sanoati vazirligiga karashli Paxta sellyulozasi kimyosi va texnologiyasi ilmiy- tekshirish institutiga (NIIXTS) kichik ilmiy xodim vazifasiga ishga olinadi. Shu institutda katta ilmiy xodim, sektor mudiri, laboratoriya mudiri va boʻlim boshligʻi vazifalarida ishlaydi.\n" +
            "Gʻ.Raxmonberdiev 1983 yilda «Suvda eruvchan asetil¬sellyuloza va uning xosilalari» mavzusida doktorlik dissertasiyasini muvaffaqiyatli himoya qiladi.\n" +
            "1991 yili Toshkent Kime-texnologiya instituti fizik va kolloid kimyo kafedrasining mudiri qilib tayinlanadi.\n" +
            "Professor Gʻ.Raxmonberdiev tomonidan paxta sellyulozasining kimyosi sohasida noyob yangi bir yoʻnalish rivojlantirildi, sellyulozaning suvda eriydigan yangi xosilalarini olish usullari ishlab chiqildi, sanoatda va xalq xoʻjaligida ularni ishlatish istiqbollari aniqlab berildi. Birinchi marta sellyuloza efirlarining suvda erish omillari koʻrib chiqildi va aniqlandi. Olingan yangi qonuniyatlar nafaqat sellyuloza efirlarining, balki yuqori molekulali birikmalarning suvda erish sabablarini tushuntirishda ham katta nazariy axamiyatga ega boʻldi.\n" +
            "Birinchi marta sellyulozaning bir nechta (10 ga yaqin) suvda eriydigan yangi efirlari olindi va ularga kimyoviy bugʻ bilan kichik molekulali dorivor moddalar ulab virus, rak va sil kasalliklarini tuzatadigan, qon ketishini keskin toʻxtatadigan fiziologik aktiv polimer materiallar olindi.\n" +
            "Moskvadagi Gamaleya nomli Mikrobiologiya va epidemiologiya instituti Oʻzbekiston Milliy universiteti va Oʻzbekiston Onkologiya va radiologiya instituti olimlari bilan hamkorlikda virus (gepatit) kasalligiga qarshi ishlatiladigan modda - interferon induktori «SAVRAS», koʻz raki kasalligini tuzatadigan yangi koʻz pardasi «GLP» va qon toʻxtatadigan polimer formasidagi «Lagoden» moddalari olindi. Olingan moddalar toʻliq toksiko farmakologik tekshiruvlardan oʻtib, tibbiyotda keng qoʻllashga tavsiya etildi. «SAVRAS» 1998 yilda Moskva shahrida chiqqan «Virusga karshi preparatlar» ma'lumotida eng yaxshi preparatlar qatoriga kiritildi. (F.I.Ershov. Antivirusnie preparati. Spravochnik. M.. «Medisina», s. 189).\n" +
            "Gʻ.Raxmonberdiev va uning shogirdlari sellyulozani modifikasiya qilish sohasida ham samarali ishlar olib bormoqdalar. Sellyulozaning koʻp asosli kislotalar bilan reaksiyalari oʻrganilib, bu ishlar natijasida hajm sigʻimi katta boʻlgan sorbentlar olindi va ular oqsillarni tozalashda, sanoat oqava suvlaridan ogʻir metall ionlarini va radionuklidlarni ajratib olishda ionitlar sifatida ishlatib koʻrildi (NIIXTBAV, Novosibirsk sh.). Moskvaning 1-sonli chit fabrikasida yonmaydigan matolar, Fargʻona kimyo tolasi korxonasida anetilsellyuloza asosida fasonli uragan tolalar olish texnologiyalari sinovdan oʻtkazildi.\n" +
            "2004 yilda professor Gʻ.Raxmonberdiev tomonidan institutda yangi «Sellyuloza va yogʻochsozlik texnologiyasi» kafedrasi tashkil etildi va unga mudir qilib tayinlandi. Bu kafedra tashkil etilgandan soʻng sellyuloza sohasidagi ilmiy-tadqiqot ishlari yanada rivojlanib, bir va koʻp yillik oʻsimliklar chiqindilaridan sellyuloza va uning asosida qogʻoz, qogʻoz mahsulotlari va efirlarini olish texnologiyalari ishlab chiqildi. Jumladan, terak va topinambur (er noki) poyasidan dunyoda ilk bor kimyoviy qayta ishlashga yaroqli boʻlgan sellyuloza va ular asosida qogʻoz va qogʻoz mahsulotlari va efirlari (karboksimetil- sellyuloza, asetat va nitrosellyuloza) olinib, sanoatga tatbiq etilmoqda. Bu mahsulotlar «Namangan kogʻozi», «Karbonam» OAJ lari va \"Ulugʻ - Jahon - Baraka» kichik korxonasida sanoat miqyosida olindi; topinambur oʻsimligining pastki qismi - tuganagidan inulin va uning xosilalari nitroinulin, karboksimetilinulin va asetatinulinlar olish usullari ishlab chiqildi va ularning kimyoviy va fizikaviy xossalari oʻrganildi.\n" +
            "Ekologik muammolarni hal etish maksadida Gʻ.Raxmonberdiev oʻz hamkasblari bilan birgalikda chiqindisiz va ekologik toza texnologiyalar yaratish, sanoat chiqindilaridan va mahalliy xomashyolardan unumli foydalanish ustida ham katta ishlar olib borgan. Jumladan, «Navoiazot» RIChB da hosil boʻladigan koʻp ming tonnali sanoat chiqindilaridan rezina-texnika korxonalarida ishlatiladigan texnik uglerod oʻrnini bosa oladigan asetilen kurumini hamda kroton aldegedi asosida korroziya ingibitorlarini olish texnologiyasi yaratildi va sanoatga tatbiq etildi.\n" +
            "Gʻ.Raxmonberdiev ilmiy ishlari natijasida 2 ta monografiya, 3 ta darslik va 20 dan ortiq oʻquv va uslubiy qoʻllanmalar yaratgan. 450 dan ortiq ilmiy maqola, shu jumladan, chet ellarda (AQSh, Ruminiya, Xitoy, Turkiya, Italiya va Shvesariya) chop etgan. 20 ta mualliflik guvohnomasi va 25 ta Oʻzbekiston patentlarini olgan.\n" +
            "Oliy oʻquv yurtlari uchun «Sellyuloza - kogʻoz ishlab chiqarish texnologiyasi va jarayonlari» mutaxassisligi boʻyicha hammualliflikda yaratilgan «Kogʻoz texnologiyasi asoslari» darsligi respublika tanlovida faxrli 2-oʻrinni (2010 y.) va «Qogʻoz texnologiyasi» darsligi 3-oʻrinni (2011y.) egallagan. Uning yozgan ma'ruzalar matni Respublika tanlovida 2-oʻrinni olgan. Shu munosabat bilan unga «Institutda xizmat koʻrsatgan professor» unvoni berilgan.\n" +
            "Uzoq yillar davomida avval Sellyuloza kimyosi va texnologiyasi ilmiy-tadqiqot institutida, soʻngra Toshkent Kimyo-texnologiya institutida samarali faoliyat koʻrsatib, yuksak vatanparvarlik, fidoyilik va mehnatsevarlik fazilatlari tufayli fan va ta'lim sohalarida ilmiy pedagog kadrlar tayyorlashda va talaba yoshlarni tarbiyalashda katta yutuqlarga erishgan. Jumladan, uning rahbarligida 5 nafar fan doktori, 20 nafar fan nomzodi tayyorlandi, bulardan 5 nafari Hamdoʻstlik mamlakatlarida faoliyat koʻrsatmoqda (Rossiya, Qozogʻiston va Qirgʻiziston).\n" +
            "Gʻ.Raxmonberdiev oʻzining sermahsul faoliyati natijasida «Eng yaxshi oʻqituvchi» (1996 - 1997), «Oliy ta'lim a'lochisi» (1998), «Institutda xizmat koʻrsatgan professor» (2004), «Yil olimi» (2006) faxriy unvonlariga sazovor boʻlgan. Qozogʻiston Fanlar akademiyasining va Nyu-York Fanlar akademiyasining akademigi, Amerika kimyo jamiyatining a'zosi, Qozogʻiston Xalqlar Doʻstligi hamda A.Yassaviy nomidagi Qozogʻiston - Turkiya universitetlarining faxriy professori.\n"
    }
];
export default dataChemists1Element